## Lovelace-UI file for Home Assistant, Settings view
## Type: Home Assistant yaml file
## Date added: 2019-07-21
## Author: R.Bisschops

title: Settings
icon: "mdi:cog-outline"
background: "#e3e3e3"
cards:
  - type: vertical-stack
    cards:
    # - type: markdown
    #   content: >
    #     ## Algemene instellingen
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Algemene instellingen
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      entities:
      - entity: input_boolean.alarm_reset_alarm
        name: Reset alarmen
        icon: "mdi:autorenew"
      - entity: input_boolean.notifications_notifications_allowed
        name: Tekst notificaties
        icon: "mdi:bell"
      - entity: input_boolean.mode_holiday 
        name: Vakantie mode
        icon: "mdi:briefcase"
      - entity: input_boolean.mode_christmas
        name: Kerst mode
        icon: "mdi:pine-tree"
      - entity: input_boolean.media_recording_mode
        name: Recorder mode
        icon: "mdi:video"
      # - entity: input_boolean.light_livingroom_state
      #   name: Licht aan status
      #   icon: "mdi:lightbulb"

  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Timers woonkamer
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      entities:
        - entity: input_number.light_livingroom_short_timer
          name: Woonkamer uit (min)
        - entity: input_number.light_high_cabinets_short_timer
          name: Koof uit (min)
        - entity: input_number.light_christmas_tree_short_timer
          name: Kerstboom (min)
  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Timers buitenlamp
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      entities:
        - entity: input_number.light_porch_long_timer
          name: Uit lang (min)
        - entity: input_number.light_porch_short_timer
          name: Uit kort (min)
  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Timers halletje
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      entities:
        - entity: input_number.light_hallway_long_timer
          name: Uit lang (min)
        - entity: input_number.light_hallway_short_timer
          name: Uit kort (min)
  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Timers Media center
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      entities:
        - entity: input_number.media_media_center_delay
        - entity: input_number.media_media_wait_delay
        # - entity: input_text.media_media_delay_timer
        # - entity: input_text.media_media_wait_timer
        - entity: input_text.media_tv_radio_mode_timer
  - type: vertical-stack
    cards:
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Zigbee2mqtt
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      entities: 
      - entity: input_select.zigbee2mqtt_log_level_state
        name: Zigbee2mqtt log level 
      - entity: input_boolean.zigbee2mqtt_permit_join
        name: Zigbee joinen toegestaan
      - entity: timer.zigbee2mqtt_permit_join
        name: Resterende join tijd
