## Core configuration file for Home Assistant  
## Type: Home Assistant yaml file
## Date added: 2019-08-01
## Author: R.Bisschops

homeassistant:
  name: !secret ha_name
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: !secret system_time_zone
## Custom packages
  packages: !include_dir_named packages/

## Cloud
cloud:

## Enables configuration UI
config:

## Allows you to issue voice commands from the frontend in enabled browsers
conversation:

## Discover some devices automatically
discovery:
  ignore:
    - philips_hue

## Enables the frontend
frontend:
  themes: !include_dir_named themes

## Google
google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

## Google assistant
## Note: The api_key for manual installs is now deprecated and will be removed in 0.105. 
## To correct this you will need to remove api_key from the configuration.yaml and switch to using service_account instead.
# google_assistant:
#  project_id: !secret ga_project_name
#  api_key: !secret ga_api_key
#  exposed_domains:
#    - light
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

## Enables support for tracking state changes over time
history:

## Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#  api_password: !secret http_password
#  base_url: https://rbisschops.duckdns.org:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

## Show links to resources in log and frontend
# introduction:

## enable iOS component
ios:

## View all events in a logbook
logbook:

## Logger
logger:
  default: warning
  logs:
    homeassistant.components.mysensors: warning
    mysensors: warning
    # homeassistant.components.script: debug

## Lovelace UI
lovelace:
  mode: yaml
  ## Additional resources used
  resources:
  - url: /local/custom_cards/mini-graph-card-bundle.js?v=0.9.4
    type: module
  - url: /local/custom_cards/button-card.js?v=3.3.6
    type: module
  - url: /local/custom_cards/custom-header.js?v=1.6.7 # Update to V1.8.3
    type: module
  - url: /local/custom_cards/decluttering-card.js?v=0.6.3
    type: module
  - url: /local/custom_cards/card-mod.js?v=14 # Update to V2.0??
    type: module
  - url: /local/custom_cards/text-element.js?v=0.0.2
    type: js


## Enables a map showing the location of tracked devices
map:

mobile_app:

## External MQTT broker (mosquitto)
mqtt:
  broker: !secret ip_mqtt_broker_hs
  username: !secret userid_mqtt_broker
  password: !secret password_mqtt_broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

## MySensors gateway
# mysensors:
#   gateways:
#     - device: !secret ip_mysensors
#       # persistence_file: 'mysensors.json'
#       nodes:
#         2:
#           name: Watermeter (MYS)
#         4:
#           name: 'Light sensor (test)'
#   version: 2.3

## Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

## Track the sun
sun:

## System health
system_health:

## Text to speech
tts:
  - platform: google_translate
    service_name: google_say

zwave:
  usb_path: /dev/ttyACM1
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key
  
updater:
## Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

## Xiaomi Gateways
# xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - mac: !secret mac_bridge_xiaomi >> leave commented for now!!
#      host: !secret ip_xiaomi_aquara
#      key: !secret xiaomi_aquara_key

## Configuations items (presence, Sensors, groups, automations and scripts)
device_tracker: !include device_trackers.yaml

## OLD STUFF, MIGRATE TO ABOVE ###

## Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

## Checks for available updates
## Note: This component will send some information about your system to
## the developers to assist with development of Home Assistant.
## For more information, please see:
## https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
