## Lovelace-UI file for Home Assistant
## Type: Home Assistant yaml file
## Date added: 2019-12-14
## Author: R.Bisschops

###############################################################################
##  Custom header settings
##  https://maykar.github.io/custom-header/#configuration/config
###############################################################################
custom_header:
  compact_mode: true
  hide_header: false
  disabled_mode: false
  voice_hide: false

###############################################################################
##  Imported custom button card templates
###############################################################################
button_card_templates:
  !include lovelace/templates/button_card_templates.yaml

###############################################################################
##  Imported settings for Declustering-card
###############################################################################
decluttering_templates:
  !include lovelace/templates/declutering_card_templates.yaml

###############################################################################
##  Main Lovelace settings
###############################################################################
title: Bisschops Mansion
# views:
views: !include_dir_list lovelace/01_standard/views
