## Package file for Home Assistant, used for miscellaneous configs
## Type: Home Assistant yaml file
## Date added: 2019-11-06
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
  

###############################################################################
##  Entities
###############################################################################
input_boolean:
  ## Holiday mode toggle switch, used for setting when on holiday 
  ## Several automations depend on this
  holiday_mode:
    name: Vakantie mode aan
    icon: mdi:toggle-switch

  ## Christmas mode toggle switch, used for setting when on ehem the holiday season is there 
  ## Several automations depend on this
  christmas_mode:
    name: Kerst periode
    icon: mdi:toggle-switch

binary_sensor:
  ## Definition of workdays with the workday sensor
  ## Used in several automations
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri, sat]
    excludes: [sun]

  ## Definition of the GFT (Bio) garbage bin
  ## Depends on google calendar for afval_kalender
  ## Used for sending "put the bin out" notifications
  - platform: template
    sensors:
      garbage_bin_gft:
        friendly_name: GFT bak
        value_template: >-
          {% if is_state('calendar.afval_kalender', 'on') %}
            {% if state_attr('calendar.afval_kalender', 'message') == 'GFT' %}
              true
            {% elif state_attr('calendar.afval_kalender', 'message') == 'GFT + PMD' %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        entity_picture_template: >-
          {{ '/local/custom_icons/gft48_' ~ states.binary_sensor.garbage_bin_gft.state ~ '.png' }}

  ## Definition of the PMD (Platic and metal) garbage bin
  ## Depends on google calendar for afval_kalender
  ## Used for sending "put the bin out" notifications
  - platform: template
    sensors:
      garbage_bin_pmd:
        friendly_name: PMD bak
        value_template: >-
          {% if is_state('calendar.afval_kalender', 'on') %}
            {% if state_attr('calendar.afval_kalender', 'message') == 'PMD' %}
              true
            {% elif state_attr('calendar.afval_kalender', 'message') == 'GFT + PMD' %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        entity_picture_template: >-
          {{ '/local/custom_icons/pmd48_' ~ states.binary_sensor.garbage_bin_pmd.state ~ '.png' }}

  ## Definition of the PMD and GFT (Plastic and metal and bio) garbage bins
  ## Depends on google calendar for afval_kalender
  ## Used for sending "put both bins out" notifications
  - platform: template
    sensors:
      garbage_bin_gft_pmd:
        friendly_name: 'GFT en PMD bak'
        value_template: >-
          {% if is_state('calendar.afval_kalender', 'on') %}
            {% if state_attr('calendar.afval_kalender', 'message') == 'GFT + PMD' %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}

###############################################################################
##  Groups
###############################################################################


###############################################################################
##  Automations
###############################################################################
automation:
  ## Automation for runnning the bed time script 
  ## Called by Alexa via HA Bridge
  - alias: "Mode bed time triggered"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.habridge_bed_time
      to: "on"
    action:
      - service: script.turn_on
        entity_id: script.mode_bed_time_triggered

  ## Automation for running the coming home script
  ## Called by the front door sensor
  - alias: "Mode coming home triggered"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.door_front_door
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.livingroom_lights
          state: "off"
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.presence_state_ralph
              state: "Just Arrived"
            - condition: state
              entity_id: input_select.presence_state_anneke
              state: "Just Arrived"
            - condition: state
              entity_id: input_select.presence_state_kimberly
              state: "Just Arrived"
    action:
      - service: script.turn_on
        entity_id: script.mode_coming_home_triggered

  ## Automation for runnning the leaving script
  ## Called by Alexa via HA Bridge
  - alias: "Mode leaving triggerred"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.habridge_leaving
      to: "on"
    action:
      - service: script.turn_on
        entity_id: script.mode_leaving_triggered

  ## Automation for runnning the extended away script
  ## Called from binary sensor Extended Away
  ## Note: Potentially replace binary_sensor.presence_everybody_extended_away with a group
  - alias: "Mode extended away triggered"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.presence_everybody_extended_away
      to: "on"
    action:
      - service: script.turn_on
        entity_id: script.mode_extended_away_triggered

  ## Automation for running the sunset script
  ## Triggered based on sunset minus offset 
  - alias: "Mode sunset triggered"
    initial_state: "on"
    trigger:
      platform: sun
      event: sunset
      offset: "-01:00:00"
    action:
      - service: script.turn_on
        entity_id: script.sun_sunset

  ## Automation to run when the garbage bins need to go out for collection
  ## Tiggered by sensors based on Google calendar entries
  - alias: "Notification garbage bin outside"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.garbage_bin_gft
      - binary_sensor.garbage_bin_pmd
      - binary_sensor.garbage_bin_gft_pmd
      to: "on"
    action:
      - service_template: >
          {% if (is_state('input_select.presence_state_ralph', 'Home')) and (is_state('input_select.presence_state_anneke', 'Home'))  %}
            script.notify_telegram_ralph_and_anneke
          {% elif is_state('input_select.presence_state_ralph', 'Home') %}
            script.notify_telegram_ralph
          {% elif is_state('input_select.presence_state_anneke', 'Home') %}
            script.notify_telegram_anneke
          {% endif %}
        data_template:
          value1: "Vandaag moet de {{ trigger.to_state.attributes.friendly_name }} bak buiten worden gezet"
          value2: ""
          value3: ""

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################
script:
  ## Script running when we go to bed, sets the house in sleep mode
  mode_bed_time_triggered:
    alias: Mode bedtime gestart
    sequence:
      ## Switch off the outdoor lighting
      - service: homeassistant.turn_off
        entity_id: input_boolean.gardenlight
      ## Switch off the christmastree
      - service: homeassistant.turn_off
        entity_id: input_boolean.christmastree
        ## Switch off the living room lights
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights
      ## Change the climate settings for the toilet heating
      - service: input_select.select_option
        data:
          entity_id: input_select.climate_restroom_heating_mode
          option: "Spaarstand"
      - condition: state
        entity_id: input_boolean.recording_mode
        state: "off"
      - service: homeassistant.turn_off
        entity_id: switch.tradfri_media_switch

  ## Script when leaving home, also called when everybody is away (from package_presence)
  mode_leaving_triggered:
    alias: Mode vertrekken gestart
    sequence:
      ## Switch off the outdoor lighting
      - service: homeassistant.turn_off
        entity_id: input_boolean.gardenlight
      ## Switch off the living room lights
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights
      ## Change the climate settings for the toilet heating
      - service: input_select.select_option
        data_template:
          entity_id: input_select.climate_restroom_heating_mode
          option: >
            {{ 'Uitgeschakeld' if is_state('input_select.climate_restroom_heating_mode','Uitgeschakeld') else 'Spaarstand' }}
      - service_template: >
          {% if is_state('input_boolean.recording_mode', 'on') %}
            homeassistant.turn_on
          {% elif is_state('input_boolean.recording_mode', 'off') %}
            homeassistant.turn_off
          {% endif %}
        entity_id: switch.tradfri_media_switch
      ## Turn on lighting, but only when dark
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      ## Switch on the outdoor lighting
      - service: homeassistant.turn_on
        entity_id: input_boolean.porchlight
      - service: timer.start
        data_template:
          entity_id: timer.light_porch
          # duration: '00:{{ states.input_text.light_porch_short_timer.state | int }}:00'
          duration: "00:{{ states('input_text.light_porch_short_timer')|int}}:00"
      - service: homeassistant.turn_on
        entity_id: input_boolean.hallwaylight
      - service: timer.start
        data_template:
          entity_id: timer.light_hallway
          # duration: '00:{{ states.input_text.media_hallway_light_long_timer.state | int }}:00'
          duration: "00:{{ states('input_text.media_hallway_light_long_timer')|int}}:00"
  ## Script when someone comes home
  mode_coming_home_triggered:
    alias: Mode thuiskomen gestart
    sequence:
      ## Change the climate settings for the toilet heating  
      - service: input_select.select_option
        data_template:
          entity_id: input_select.climate_restroom_heating_mode
          option: >
            {{ 'Uitgeschakeld' if is_state('input_select.climate_restroom_heating_mode','Uitgeschakeld') else 'Verwarmen' }}
      ## Turn on lighting, but only when dark
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      ## Switch on the outdoor lighting
      - service: homeassistant.turn_on
        entity_id: input_boolean.gardenlight
      - service: homeassistant.turn_on
        entity_id:
          - input_boolean.livingroom_lights_status
      ## Switch on the living room lights
      # - service: homeassistant.turn_on
      #   entity_id: input_boolean.livingroom_lights
      - service: script.light_hue_set_scene_automatic
        data_template:
          brightness_value: >
            {{ '100,150' }}
          profile_value: >
            {{ 'christmas' if is_state('input_boolean.christmas_mode','on') else 'normal' }}
          transition: 2
      ## Turn on the high cabinets lights
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.highcabinets
          # - switch.tradfri_high_cabinets_switch
      ## Switch on the living room lights switch
      - service: homeassistant.turn_on
        entity_id: input_boolean.livingroom_lights
      ## check if it is christmas time
      - condition: state
        entity_id: input_boolean.christmas_mode
        state: "on"
      ## Switch on the chritmas tree lights
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.christmastree

  ## Script everybody extended away
  mode_extended_away_triggered:
    alias: Mode iedereen langere tijd weg gestart
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.climate_restroom_heating_mode
          option: "Uitgeschakeld"
      - service: homeassistant.turn_on
        entity_id: input_boolean.holiday_mode

  ## Script running at sunset
  sun_sunset:
    alias: Zonsondergang bereikt
    sequence:
      - condition: state
        entity_id: binary_sensor.presence_people_home
        state: "on"
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.livingroom_lights_status
        state: "off"
      ## Switch on the living room lights switch
      - service: homeassistant.turn_on
        entity_id: input_boolean.livingroom_lights_status
      ## start hue lampen met de juiste mode
      - service: script.light_hue_set_scene_transition
        data_template:
          brightness_start_value: >
            {{ '1,1' }}
          brightness_stop_value: >
            {{ '90,100' if is_state('input_select.light_livingroom_mode','Video') else '100,150' }}
          profile_start_value: >
            {{ 'christmas' if is_state('input_boolean.christmas_mode','on') else 'normal' }}
          profile_stop_value: >
            {{ 'christmas' if is_state('input_boolean.christmas_mode','on') else 'normal' }}
          transition: 1800
      # - service: script.hue_sunset_mode
      ## start timer for kitchen cabinets, will switch on after xx hour
      - service: timer.start
        data_template:
          entity_id: timer.light_high_cabinets_on
          duration: "00:30:00"
      ## Switch on the living room lights switch
      - service: homeassistant.turn_on
        entity_id: input_boolean.livingroom_lights
      ## check if it is christmas time
      - condition: state
        entity_id: input_boolean.christmas_mode
        state: "on"
      ## start timer for christmas tree, will switch on after xx hour
      - service: timer.start
        data_template:
          entity_id: timer.switch_christmastree_on
          duration: "00:30:00"

  ##----------------------------------------------
  ## Test scripts >> Remove ASAP after testing 
  ##----------------------------------------------
  
  light_hue_test:
    alias: hue test
    sequence:
      ## start hue lampen met de juiste mode
      - service: script.light_hue_set_scene_transition
        data_template:
          brightness_start_value: >
            {{ '1,1' }}
          brightness_stop_value: >
            {{ '100,150' }}
          profile_start_value: concentrate
          profile_stop_value: relax
          transition: 5

  light_hue_test_auto:
    alias: hue test
    sequence:
      ## start hue lampen met de juiste mode
      - service: script.light_hue_set_scene_automatic
        data_template:
          brightness_value: >
            {{ '50,50' if is_state('input_select.light_livingroom_mode','Video') else '100,150' }}
          profile_value: >
            {{ 'christmas' if is_state('input_boolean.christmas_mode','on') else 'concentrate' }}
          transition: 5

###############################################################################
##  Timers
###############################################################################

