## Package file for Home Assistant, used for setting the Hue scenes  
## Type: Home Assistant yaml file
## Date added: 2019-11-11
## Author: R.Bisschops
##
## Notes: Scenes are also stored in the Hue Bridge and can be
## edited with the Hue V1 and/or V2 App

###############################################################################
##  Homeassistant settings
###############################################################################

homeassistant:
  customize:
    script.light_hue_sent_scene_to_hue_bridge:
      icon: mdi:lightbulb

## Hue bridges and emulators
hue:
  bridges:
    - host: !secret ip_hue_bridge
      # filename: phue_bridge.conf
      allow_unreachable: true
      allow_hue_groups: true

###############################################################################
##  Entities
###############################################################################

input_boolean:
  ## Input booleans used for selecting the scene for the Hue lamps
  ## Used in the UI and in the script hue_set
  light_normal_scene:
    name: Normaal licht scene
  light_relax_scene:
    name: Ontspannen licht scene
  light_reading_scene:
    name: Lezen licht scene
  light_concentrate_scene:
    name: Concentratie licht scene
  light_cleaning_scene:
    name: Schoonmaken licht scene
  light_dimmed_scene:
    name: Gedimd licht scene
  light_energy_scene:
    name: Energie licht scene
  light_clear_scene:
    name: Helder licht scene
  light_nightlight_scene:
    name: Nachtlampje licht scene
  light_christmas_scene:
    name: Kerst licht scene

##-----------------------------------------------------------------------------------------------
## Updated and changed entities - input_boolean
##-----------------------------------------------------------------------------------------------


## Input selectors for scenes and Rooms
input_select:
  ## Selector for setting the previous state of selector switches. Used for toggling them
  ## off when a new scene is selected. Used in the script hue_set.
  light_scene_old_state:
    name: Oude hue scene
    icon: mdi:lightbulb
    options:
      - normal
      - relax
      - reading
      - concentrate
      - cleaning
      - dimmed
      - energy
      - clear
      - nightlight
      - christmas
  ## Selector for setting the current state of selector switches. Used for toggling them
  ## on when a new scene is selected. Used in the script hue_set.
  light_scene_current_state:
    name: Nieuwe hue scene
    icon: mdi:lightbulb
    options:
      - normal
      - relax
      - reading
      - concentrate
      - cleaning
      - dimmed
      - energy
      - clear
      - nightlight
      - christmas

  ## Mode selector for the lights in the livingroom.
  ## Used for the modes the light can be set to from media center
  light_livingroom_mode:
    name: Verlichtsmode Woonkamer
    options:
      - Normaal
      - Video
    initial: Normaal
    icon: mdi:lightbulb

##-----------------------------------------------------------------------------------------------
## Updated and changed entities - input_select
##-----------------------------------------------------------------------------------------------
  ## Selector for the scene for the Hue lighting.
  light_livingroom_scene:
    name: Nieuwe hue scene
    icon: mdi:lightbulb
    options:
      - Normaal
      - Ontspannen
      - Lezen
      - Concentreren
      - Schoonmaken
      - Gedimd
      - Energie
      - Helder
      - Nachtlampje
      - Kerst

##-----------------------------------------------------------------------------------------------
## Depricated entities - input_select
##-----------------------------------------------------------------------------------------------

## Classic selectors for scenes and Rooms (used to manage the HUe bridge scenes)
  light_hue_scenes:
    name: Hue licht scenes
    icon: mdi:lightbulb
    options:
      - Concentratie
      - Energie
      - Gedimd
      - Helder 
      - Lezen
      - Nachtlampje
      - Ontspannen
      - Schoonmaken
      - TV mode
      - Verlichting aan
      - Zonsondergang
    initial: Verlichting aan
  light_hue_groups:
    name: Hue selectie ruimte
    icon: mdi:group
    options:
      - Woonkamer
      - Keuken
    initial: Woonkamer
##-----------------------------------------------------------------------------------------------

light:
  ## light groups for setting the Hue lights. Present itself as light.xxx 
  - platform: group
    name: Woonkamer Hue
    entities:  
      - light.lage_kast_links
      - light.lage_kast_rechts
      - light.staande_lamp_links
      - light.staande_lamp_rechts
  - platform: group
    name: light low cabinets
    entities:
      - light.lage_kast_links
      - light.lage_kast_rechts
  - platform: group
    name: light standing lights
    entities:
      - light.staande_lamp_links
      - light.staande_lamp_rechts

###############################################################################
##  Groups
###############################################################################


###############################################################################
##  Automations
###############################################################################
automation:
  ## Automation for selecting the Hue scenes form the UI
  # - alias: "Light - scene lighting livingroom"
  #   initial_state: "on"
  #   trigger:
  #     platform: state
  #     entity_id:
  #       - input_boolean.light_normal_scene
  #       - input_boolean.light_relax_scene
  #       - input_boolean.light_reading_scene
  #       - input_boolean.light_concentrate_scene
  #       - input_boolean.light_cleaning_scene
  #       - input_boolean.light_dimmed_scene
  #       - input_boolean.light_energy_scene
  #       - input_boolean.light_clear_scene
  #       - input_boolean.light_nightlight_scene
  #       - input_boolean.light_christmas_scene
  #     to: "on"
  #   action:
  #     - service: script.light_hue_set_scene_from_buttons
  #       data_template:
  #         new_scene: >
  #           {% set trigger = trigger.to_state.object_id|replace("_scene","")|replace("light_","") %}
  #           {{ trigger }}
  #         old_scene: "{{ states.input_select.light_scene_current_state.state }}"

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################

script:
  ## Set hue scene based on button from lovelace home tab
  ## Called from automation.scene_verlichting_woonkamer
  # light_hue_set_scene_from_buttons:
  #   alias: Set Hue scenes vanuit home knoppen
  #   sequence:
  #     - condition: template
  #       value_template: >-
  #         {% if new_scene == old_scene %}
  #           false
  #         {% else %}
  #           true
  #         {% endif %}
  #     - service: input_select.select_option
  #       data_template:
  #         entity_id: input_select.light_scene_old_state
  #         option: "{{ old_scene }}"
  #     - service: input_select.select_option
  #       data_template:
  #         entity_id: input_select.light_scene_current_state
  #         option: "{{ new_scene }}"
  #     - service: input_boolean.turn_off
  #       data_template:
  #         entity_id: >-
  #           {% set entity = "input_boolean.light_" ~ old_scene ~ "_scene" %}
  #           {{ entity }}
  #     - service: script.light_hue_set_scene_manual
  #       data_template:
  #         profile_value: >
  #           {{ new_scene }}

  ## Script for setting Hue lamps in video or normal mode
  ## used in package_media_center
  # light_hue_mode_change:
  #   alias: Licht aanpassen voor video of normale mode
  #   sequence:
  #     - service: script.light_hue_set_scene_automatic
  #       data_template:
  #         brightness_value: >
  #           {{ '90,100' if is_state('input_select.light_livingroom_mode','Video') else '100,150' }}
  #         profile_value: >
  #           {{ 'christmas' if is_state('input_boolean.mode_christmas','on') else 'normal' }}
  #         transition: 5

  ## Script for setting Hue lamps from a mode into a new mode
  ## Usage: call this script from any other automation or script.
  ## Variables: brightness_start_value, brightness_stop_value, profile_value
  # light_hue_set_scene_transition:
  #   alias: Set hue mode via overgang
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_low_cabinets
  #         brightness: >
  #           {{ brightness_start_value.split(',')[0]|int }}
  #         profile: >
  #           {{ '{}_1'.format(profile_start_value) }}
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_standing_lights
  #         brightness: >
  #           {{ brightness_start_value.split(',')[1]|int }}
  #         profile: >
  #           {{ '{}_2'.format(profile_start_value) }}
  #     - delay:
  #         seconds: 1
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_low_cabinets
  #         brightness: >
  #           {{ brightness_stop_value.split(',')[0]|int }}
  #         profile: >
  #           {{ '{}_1'.format(profile_stop_value) }}
  #         transition: "{{ transition|float }}"
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_standing_lights
  #         brightness: >
  #           {{ brightness_stop_value.split(',')[1]|int }}
  #         profile: >
  #           {{ '{}_2'.format(profile_stop_value) }}
  #         transition: "{{ transition|float }}"

  ## Script for setting Hue lamps into a new mode (from off)
  ## Usage: call this script from any other automation or script.
  ## Variables: brightness_value, profile_value
  # light_hue_set_scene_automatic:
  #   alias: Set hue mode overgang naar andere scene
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_low_cabinets
  #         brightness: >
  #           {{ brightness_value.split(',')[0]|int }}
  #         profile: >
  #           {{ '{}_1'.format(profile_value) }}
  #         transition: "{{ transition|float }}"
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_standing_lights
  #         brightness: >
  #           {{ brightness_value.split(',')[1]|int }}
  #         profile: >
  #           {{ '{}_2'.format(profile_value) }}
  #         transition: "{{ transition|float }}"

  ## Script for setting Hue lamps into a new mode (manually initiated for UI)
  ## Usage: call this script from any other automation or script. 
  ## Variables: profile_value
  # light_hue_set_scene_manual:
  #   alias: Set hue mode handmatig
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_low_cabinets
  #         profile: >
  #           {{ '{}_1'.format(profile_value) }}
  #         transition: 2
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: light.light_standing_lights
  #         profile: >
  #           {{ '{}_2'.format(profile_value) }}
  #         transition: 2

##-----------------------------------------------------------------------------------------------
## Test scripts >> Remove ASAP after testing 
##-----------------------------------------------------------------------------------------------

  ## Test script for setting Hue lamps
  ## used in package_livingroom
  light_light_adjust_test:
    alias: licht test aanpassen
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.light_low_cabinets
          brightness: 1
          xy_color: [0.3698, 0.3723]
      - delay:
          seconds: 1
      - service: light.turn_on
        data_template:
          entity_id: light.light_low_cabinets
          brightness: 255
          transition: 10

##-----------------------------------------------------------------------------------------------
## Depricated scripts
##-----------------------------------------------------------------------------------------------

  ## Script for setting the Hue scene manual
  ## Deprecated script
  light_hue_manual_set_scene:
    alias: Set Hue scenes handmatig
    sequence: 
      - service: script.light_hue_sent_scene_to_hue_bridge
        data_template:
          group: "{{ states.input_select.light_hue_groups.state }}"
          name: "{{ states.input_select.light_hue_scenes.state }}"

  ## Script for setting the Hue scene manual
  ## used by multiple packages (media_center)
  ## Deprecated script
  light_hue_sent_scene_to_hue_bridge:
    alias: Send Hue scene naar Hue Bridge
    sequence: 
      - service: hue.hue_activate_scene
        data_template:
          group_name: "{{ group }}"
          scene_name: "{{ name }}"
##-----------------------------------------------------------------------------------------------

###############################################################################
##  Timers
###############################################################################

