## Package file for Home Assistant, used for energy monitoring
## Type: Home Assistant yaml file
## Date added: 2020-03-24
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Utilities sensors
    sensor.utilities_water:
      friendly_name: Water meter
    sensor.dsmr_reading_electricity_currently_delivered_watt:
      friendly_name: Huidig verbruik
    ## Utilities usage sensors
    sensor.utilities_day_consumption_water_costs:
      friendly_name: Kosten dagvebruik water
    sensor.utilities_water_usage:
      friendly_name: Water verbruik
    ## Reference values
    sensor.utilities_reference:
      friendly_name: Referentie (E, G, W)
    sensor.utilities_total_cost_day:
      friendly_name: Totale kosten per dag (E, G, W)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

###############################################################################
#  Entities
###############################################################################
input_number:
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Active
  ##-----------------------------------------------------------------------------------------------
  utility_water_tariff:
    name: Tarief water (EUR/m3)
    initial: 0.927
    min: 0
    max: 2
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Obsolete
  ##-----------------------------------------------------------------------------------------------

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## DSMR reader integration
  - platform: dsmr_reader
  ## Utilities sensor water
  - platform: "mqtt"
    name: utilities_water
    state_topic: "home/meter/water"
    expire_after: 3600             # 1 hours
    force_update: true
    value_template: "{{ value_json.usage }}"
    json_attributes_topic: "home/meter/water"
  ## Utilities water meter reference value (stored at 00:00 previous day)
  ## Source MQTT topic home/meter/reference
  - platform: "mqtt"
    name: utilities_reference
    state_topic: "home/meter/reference"
    value_template: "{{ value_json.time }}"
    json_attributes_topic: "home/meter/reference"
  ## Utilities converted readings
  - platform: template
    sensors:
      ## Current electricity usage
      ## Source: DSMR-Reader
      dsmr_reading_electricity_currently_delivered_watt:
        value_template: "{{ states('sensor.dsmr_reading_electricity_currently_delivered')|float * 1000 }}"
        unit_of_measurement: "W"
      ## Water usage current day (as of 00:00)
      ## Source: sensor.utilities water & sensor.utilities_reference
      utilities_water_usage:
        value_template: >-
          {% set previous = state_attr('sensor.utilities_reference','water') %}
          {% set value = (states('sensor.utilities_water')|float-previous['day']|float)|round %}
          {{ value }}
        unit_of_measurement: "L"
      ## Water costs current day (as of 00:00)
      ## Source: sensor.utilities_water_usage & input_number.utility_water_tariff
      utilities_day_consumption_water_costs:
        value_template: "{{(states('sensor.utilities_water_usage')|float /1000 * states('input_number.utility_water_tariff')|float)|round(2) }}"
        unit_of_measurement: "€"
      ## Utilities costs current day (E+G+W)
      ## Source: sensor.dsmr_day_consumption_total_cost & sensor.utilities_day_consumption_water_costs
      utilities_total_cost_day:
        value_template: "{{ (states('sensor.dsmr_day_consumption_total_cost')|float + states('sensor.utilities_day_consumption_water_costs')|float)|round(2) }}"
        unit_of_measurement: "€"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------

# camera:
##-----------------------------------------------------------------------------------------------
## cameras - Active
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## cameras - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## cameras - Obsolete
##-----------------------------------------------------------------------------------------------
## Camera used for displaying electricity usage graphs

  # - platform: local_file
  #   name: grafana_electricity
  #   file_path: downloads/electricity.png 
  # - platform: generic
  #   name: "Elektricteit Grafana"
  #   still_image_url: 'http://192.168.0.217:3000/render/d-solo/p7Aaxdyik/dashboard?refresh=10s&orgId=1&panelId=2&from=now-24h&to=now&width=1000&height=500&tz=Europe%2FAmsterdam'
  #   username: !secret grafana_user
  #   password: !secret grafana_pass

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################