## Package file for Home Assistant, used for getting HA-Bridge data via MQTT 
## Type: Home Assistant yaml file
## Date added: 2019-11-11
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ## Media devices from HA Bridge 
    binary_sensor.habridge_television:
      friendly_name: Televisie (via HA Bridge)
    binary_sensor.habridge_smarttv:
      friendly_name: Smart-TV (via HA Bridge)
    binary_sensor.habridge_mediaplayer:
      friendly_name: Mediaplayer (via HA Bridge)
    binary_sensor.habridge_appletv:
      friendly_name: Apple-TV (via HA Bridge)
    binary_sensor.habridge_radio:
      friendly_name: Radio (via HA Bridge)
    binary_sensor.habridge_music:
      friendly_name: Muziek (via HA Bridge)
    binary_sensor.habridge_netflix:
      friendly_name: Netflix (via HA Bridge)
    binary_sensor.habridge_spotify:
      friendly_name: Spotify (via HA Bridge)
    binary_sensor.habridge_poweroff:
      friendly_name: Poweroff (via HA-Bridge)
    ## Scenes from HA Bridge
    binary_sensor.habridge_bed_time:
      friendly_name: Bed tijd (via HA-Bridge)
    binary_sensor.habridge_leaving:
      friendly_name: Vertrekken (via HA-Bridge)
    ## Switches for living room lights (as a scene)
    binary_sensor.habridge_livingroom_lights_off:
      friendly_name: Woonkamer licht uit (via HA-Bridge)
    binary_sensor.habridge_livingroom_lights_on:
      friendly_name: Woonkamer licht aan (via HA-Bridge)

###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ## Media modes from HA Bridge
  - platform: mqtt
    name: habridge_television
    state_topic: "media_mode/television"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_smarttv
    state_topic: "media_mode/smarttv"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_netflix
    state_topic: "media_mode/netflix"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_spotify
    state_topic: "media_mode/spotify"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_mediaplayer
    state_topic: "media_mode/mediaplayer"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_appletv
    state_topic: "media_mode/appletv"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_radio
    state_topic: "media_mode/radio"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_music
    state_topic: "media_mode/music"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_poweroff
    state_topic: "media_mode/poweroff"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"

  ## Modes from HA Bridge
  - platform: mqtt
    name: habridge_bed_time
    state_topic: "scene/bed_time"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_leaving
    state_topic: "scene/leaving"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"

  ## Switches for living room lights (as a scene)
  - platform: mqtt
    name: habridge_livingroom_lights_on
    state_topic: "scene/livingroom_lights_on"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_livingroom_lights_off
    state_topic: "scene/livingroom_lights_off"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"

switch:
  ## Switch for Christmastree (from HA Bridge)
  - platform: "mqtt"
    name: habridge_christmastree
    state_topic: "switch/christmastree"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/christmastree"
  - platform: "mqtt"
    name: habridge_barlight
    state_topic: "switch/barlight"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/barlight"
  - platform: "mqtt"
    name: habridge_gardenlight
    state_topic: "switch/gardenlight"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/gardenlight"
  - platform: "mqtt"
    name: habridge_waterornament
    state_topic: "switch/waterornament"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/waterornament"
  - platform: "mqtt"
    name: habridge_hallwaylight
    state_topic: "switch/hallwaylight"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/hallwaylight"
  - platform: "mqtt"
    name: habridge_porchlight
    state_topic: "switch/porchlight"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/porchlight"
  - platform: "mqtt"
    name: habridge_highcabinets
    state_topic: "switch/highcabinets"
    payload_on: "on"
    payload_off: "off"
    command_topic: "switch/highcabinets"

##----------------------------------------------
## Test entities >> Remove ASAP after testing 
##----------------------------------------------

light:
  - platform: "mqtt"
    name: habridge_barlight
    state_topic: "light/barlight"
    payload_on: "on"
    payload_off: "off"
    brightness_state_topic: "light/barlight/level"
    command_topic: "light/barlight"

###############################################################################
##  Groups
###############################################################################


###############################################################################
##  Automations
###############################################################################


###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################


###############################################################################
##  Timers
###############################################################################

