## Package file for Home Assistant, used for presence  
## Type: Home Assistant yaml file
## Date added: 2019-11-11
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  # customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## Owntracks - Active
##-----------------------------------------------------------------------------------------------
owntracks:
  max_gps_accuracy: 200

###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Anneke home sensor
  - platform: template
    sensors:
      presence_anneke_home:
        friendly_name: Anneke thuis
        value_template: >-
          {{ is_state('input_select.presence_anneke_bisschops','Home')
            or is_state('input_select.presence_anneke_bisschops','Just Arrived')
            or is_state('input_select.presence_anneke_bisschops','Just Left') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/anneke48_' ~ states('binary_sensor.presence_anneke_home') ~ '.png' }}
  ## kimberly home sensor
  - platform: template
    sensors:
      presence_kimberly_home:
        friendly_name: Kimberly thuis
        value_template: >-
          {{ is_state('input_select.presence_kimberly_bisschops','Home')
            or is_state('input_select.presence_kimberly_bisschops','Just Arrived')
            or is_state('input_select.presence_kimberly_bisschops','Just Left') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/kimberly48_' ~ states('binary_sensor.presence_kimberly_home') ~ '.png' }}
  ## Ralph home sensor
  - platform: template
    sensors:
      presence_ralph_home:
        friendly_name: Ralph thuis
        value_template: >-
          {{ is_state('input_select.presence_ralph_bisschops','Home')
            or is_state('input_select.presence_ralph_bisschops','Just Arrived')
            or is_state('input_select.presence_ralph_bisschops','Just Left') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/ralph48_' ~ states('binary_sensor.presence_ralph_home') ~ '.png' }}
  ## Anyone home sensor
  - platform: template
    sensors:
      presence_people_home:
        friendly_name: Iemand thuis
        value_template: >-
          {{ is_state('input_select.presence_ralph_bisschops','Home')
            or is_state('input_select.presence_ralph_bisschops','Just Arrived')
            or is_state('input_select.presence_ralph_bisschops','Just Left')
            or is_state('input_select.presence_anneke_bisschops','Home')
            or is_state('input_select.presence_anneke_bisschops','Just Arrived')
            or is_state('input_select.presence_anneke_bisschops','Just Left')
            or is_state('input_select.presence_kimberly_bisschops','Home')
            or is_state('input_select.presence_kimberly_bisschops','Just Arrived')
            or is_state('input_select.presence_kimberly_bisschops','Just Left') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/people48_' ~ states('binary_sensor.presence_people_home') ~ '.png' }}
  ## Everybody is away sensor
  - platform: template
    sensors:
      presence_everybody_away:
        friendly_name: Niemand thuis (kort)
        value_template: >-
          {% set ralph = true if is_state('input_select.presence_ralph_bisschops','Extended Away') or is_state('input_select.presence_ralph_bisschops','Away') else false %}
          {% set anneke = true if is_state('input_select.presence_anneke_bisschops','Extended Away') or is_state('input_select.presence_anneke_bisschops','Away') else false %}
          {% set kimberly = true if is_state('input_select.presence_kimberly_bisschops','Extended Away') or is_state('input_select.presence_kimberly_bisschops','Away') else false %}
          {{ 'on' if ralph == true and anneke == true and kimberly == true else 'off' }}
        entity_picture_template: >-
          {{ '/local/custom_icons/people48_' ~ states('binary_sensor.presence_people_home') ~ '.png' }}
  ## Everybody is extended away sensor
  - platform: template
    sensors:
      presence_everybody_extended_away:
        friendly_name: Niemand thuis (lang)
        value_template: >-
          {{ is_state('input_select.presence_ralph_bisschops','Extended Away')
            and is_state('input_select.presence_anneke_bisschops','Extended Away')
            and is_state('input_select.presence_kimberly_bisschops','Extended Away') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/people48_' ~ states('binary_sensor.presence_people_home') ~ '.png' }}

  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------

input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ## Ralph advanced home sensor (added for Node_RED)
  presence_ralph_bisschops:
    name: Ralph
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  ## Anneke advanced home sensor (added for Node_RED)
  presence_anneke_bisschops:
    name: Anneke
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  ## Kimberly advanced home sensor (added for Node_RED)
  presence_kimberly_bisschops:
    name: Kimberly
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################