## Package file for Home Assistant, used for the storage area
## Type: Home Assistant yaml file
## Date added: 2019-11-17
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
  ##-----------------------------------------------------------------------------------------------
  ## Customizations - Active
  ##-----------------------------------------------------------------------------------------------
    ## Mailbox vibration sensor
    ## Souce: Xiaomi vibration sensor ZigBee
    sensor.vibration_mailbox:
      friendly_name: Brievenbus
    sensor.vibration_mailbox_battery:
      friendly_name: Brievenbus (batterij)
    sensor.vibration_mailbox_linkquality:
      friendly_name: Brievenbus (link quality)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Button porch light
  ## Source: template switch
  light_porch_button:
    name: Buitenlamp
    icon: mdi:lightbulb
  ## Status monitoring porch light
  ## Source: template switch
  light_porch:
    name: Buitenlamp
    icon: mdi:lightbulb
  ## Storage door delayed open
  ## Source: template switch
  door_storage_door_delayed:
    name: Berging deur vetraagd
    icon: mdi:door
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Test
  ##-----------------------------------------------------------------------------------------------

input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ## State indicator porch light
  ## Source: template input select 
  light_porch:
    name: Buitenlamp
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"

input_number:
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Active
  ##-----------------------------------------------------------------------------------------------
  ## Long timer porch light lights (used in Node_RED)
  ## Source: template
  light_porch_long_timer:
    name: Buitenlamp timer lang (min)
    initial: 10
    min: 1
    max: 30
    step: 1 
  ## Short timer hallway lights (used in Node_RED)
  ## Source: template
  light_porch_short_timer:
    name: Buitenlamp timer kort (min)
    initial: 5
    min: 1
    max: 30
    step: 1
  ## Porch light oof delay (used in Node_RED)
  ## Source: template
  light_porch_off_delay:
    name: Buitenlamp uit vertraging (sec)
    initial: 1
    min: 0
    max: 10
    step: 0.5
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Obsolete
  ##-----------------------------------------------------------------------------------------------

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Mailbox vibration sensor
  ## Souce: Xiaomi vibration sensor ZigBee
  - platform: "mqtt"
    name: vibration_mailbox
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
  - platform: "mqtt"
    name: vibration_mailbox_linkquality
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------
##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################