## Package file for Home Assistant, used for testing and test sensors
## Type: Home Assistant yaml file
## Date added: 2021-01-13
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Test environment sensor
    ## Source: Dummy 
    sensor.environment_test_temperature:
      friendly_name: Temperatuur Test
    sensor.environment_test_humidity:
      friendly_name: Rel. Vochtigheid Test
    sensor.environment_test_pressure:
      friendly_name: Luchtdruk Test
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Test
    ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ## Test environment sensor
  ## Source: Dummy
  environment_test_humidity_state:
    name: Luchtvochtigheid Test status
    options: 
      - Te laag
      - Laag
      - Normaal
      - Hoog
      - Te hoog
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------
sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Test environment sensor
  ## Source: Dummy 
  - platform: "mqtt"
    name: environment_test_temperature
    state_topic: "test/test_sensor_env"
    expire_after: 900
    force_update: true
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    name: environment_test_humidity
    state_topic: "test/test_sensor_env"
    expire_after: 900
    force_update: true
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: environment_test_pressure
    state_topic: "test/test_sensor_env"
    expire_after: 900
    force_update: true
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Test
  ##-----------------------------------------------------------------------------------------------
###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################