## Package file for Home Assistant, used for all alarm sensors and
## associated automations and scripts
## Type: Home Assistant yaml file
## Date added: 2020-02-26
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Refridgerator door sensors
    ## Source: Xiaomi Aqara ZigBee
    binary_sensor.door_refrigerator:
      friendly_name: Koelkast deur
    sensor.door_refrigerator_linkquality:
      friendly_name: Koelkastdeur (link quality)
    ## Office motion sensors
    ## Source: Xiaomi Aqara ZigBee
    binary_sensor.motion_office:
      friendly_name: Bewegingssensor kantoor
    sensor.motion_office_linkquality:
      friendly_name: Bewegingssensor kantoor (link quality)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Future use
    ##-----------------------------------------------------------------------------------------------
    # ## Freezer door sensors
    # binary_sensor.door_freezer:
    #   friendly name: Vriezer deur
    # sensor.door_freezer_linkquality:
    #   friendly_name: Vriezer deur (link quality)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

###############################################################################
#  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Refridgerator door 
  ## Source: Xiaomi Aqara ZigBee
  - platform: mqtt
    name: door_refrigerator
    state_topic: "zigbee2mqtt/aqara_refrigerator_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
  ## Office motion sensor 
  ## Source: Xiaomi Aqara ZigBee
  - platform: mqtt
    name: motion_office
    state_topic: "zigbee2mqtt/mijia_office_motion"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"
  ## Alarm state, used for lovelace tab Home
  ## Source: template
  - platform: template
    sensors:
      alarm_generic_alarm:
        friendly_name: Algemeen alarm
        value_template: >-
          {{ is_state('input_boolean.alarm_generic_alarm', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/alarm48_' ~ states('input_boolean.alarm_generic_alarm') ~ '.png'}}
  ## Group door open sensors (monitors all outside doors)
  ## Source: template
  - platform: template
    sensors:
      door_all_doors:
        friendly_name: Alle deuren
        value_template: >-
          {{ is_state('binary_sensor.door_front_door', 'on')
            or is_state('binary_sensor.door_storage_door', 'on')
            or is_state('input_boolean.dummy_garden_door', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/door48_' ~ states('binary_sensor.door_all_doors') ~ '.png'}}
  ## Group window open sensors (monitors all windows)
  ## Source: template
  - platform: template
    sensors:
      door_all_windows:
        friendly_name: Alle ramen
        value_template: >-
          {{ is_state('input_boolean.dummy_groundfloor_front_window', 'on')
            or is_state('input_boolean.dummy_office_window', 'on')
            or is_state('input_boolean.dummy_side_room_window', 'on')
            or is_state('input_boolean.bedroom_window_l', 'on')
            or is_state('input_boolean.bedroom_window_r', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/window48_' ~ states('binary_sensor.door_all_windows') ~ '.png'}}
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------

input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Dummy inputs for doors and windows, will be replaced with real sensors in the future
  ## Groundfloor
  ## Groudfloor window, frontside of the house 
  ## Source: Dummy switch
  dummy_groundfloor_front_window:
    name: Voorraam benedenverdieping (dummy)
    icon: mdi:window-closed-variant
  ## Door garden, location livingroom  
  ## Source: Dummy switch
  dummy_garden_door:
    name: Tuindeur (dummy)
    icon: mdi:door-closed
  ## Door hallway, location livingroom-hallway
  ## Source: Dummy switch
  dummy_groundfloor_hallway_door:
    name: Tussendeur woonkamer (dummy)
    icon: mdi:door-closed
  ## Door storage, location hallway-storage
  ## Source: Dummy switch
  dummy_hallway_storage_door:
    name: Tussendeur berging (dummy)
    icon: mdi:door-closed
  ## Door metering cabinet, location hallway
  ## Source: Dummy switch
  dummy_metering_cabinet_door:
    name: Meterkast deur (dummy)
    icon: mdi:door-closed
  ## Door rest room, location hallway
  ## Source: Dummy switch
  dummy_rest_room_door:
    name: Toiletdeur (dummy)
    icon: mdi:door-closed
  ## Door freezer, location storage
  ## Source: Dummy switch
  dummy_freezer_door:
    name: Vriezerdeur (dummy)
    icon: mdi:door-closed
  ## First floor
  ## Door bathroom, location 1st floor hallway-bathroom
  ## Source: Dummy switch
  dummy_bath_room_door:
    name: Badkamer deur (dummy)
    icon: mdi:door-closed
  ## Door master bed room, location 1st floor hallway-master bedroom
  ## Source: Dummy switch
  dummy_bed_room_door:
    name: Slaapkamer deur (dummy)
    icon: mdi:door-closed
  ## Window left, locartion master bedroom 
  ## Source: Dummy switch
  dummy_bed_room_window_left:
    name: Slaapkamer raam links (dummy)
    icon: mdi:window-closed-variant
  ## Window right, location master bedroom
  ## Source: Dummy switch
  dummy_bed_room_window_right:
    name: Slaapkamer raam rechts (dummy)
    icon: mdi:window-closed-variant
  ## Door hallway, location 1st floor hallway
  ## Source: Dummy switch
  dummy_first_floor_hallway_door:
    name: Tussendeur 1e verdieping (dummy)
    icon: mdi:door-closed
  ## Door office, location 1st floor hallway-office
  ## Source: Dummy switch
  dummy_office_door:
    name: Kantoor deur (dummy)
    icon: mdi:door-closed
  ## Window office, location office
  ## Source: Dummy switch
  dummy_office_window:
    name: Kantoor raam (dummy)
    icon: mdi:window-closed-variant
  ## Window side room, location side room
  ## Source: Dummy switch
  dummy_side_room_window:
    name: Kastenkamer raam (dummy)
    icon: mdi:window-closed-variant
  ## Second floor
  ## Door heating room, location 2nd floor hallway-heating room
  ## Source: Dummy switch
  dummy_heating_room_door:
    name: Ketelkast deur (dummy)
    icon: mdi:door-closed
  ## Door bedroom, location 2nd floor hallway-bedroom
  ## Source: Dummy switch
  dummy_kims_room_door:
    name: Kamer Kim (dummy)
    icon: mdi:door-closed
  ## Window left 2nd floor bedroom, location 2nd floor bedroom
  ## Source: Dummy switch
  dummy_kims_room_window_left:
    name: Kamer Kim raam links (dummy)
    icon: mdi:window-closed-variant
  ## Window right 2nd floor bedroom, location 2nd floor bedroom
  ## Source: Dummy switch
  dummy_kims_room_window_right:
    name: Kamer Kim raam rechts (dummy)
    icon: mdi:window-closed-variant
  ## Window hallway 2nd floor, location 2nd floor hallway
  ## Source: Dummy switch
  dummy_hallway_window:
    name: Overloop raam (dummy)
    icon: mdi:window-closed-variant
  ## Dummy inputs for garbage bins, will be replaced with real sensors in the future
  ## Bio bin, test switch
  ## Source: Dummy switch
  dummy_garbage_bin_bio:
    name: GFT bak (dummy)
    icon: mdi:delete-outline
  ## Plastic bin, test switch
  ## Source: Dummy switch
  dummy_garbage_bin_plastic:
    name: PMD bak (dummy)
    icon: mdi:delete-outline
  ## Generic alarm input switch
  ## Source: Dummy
  alarm_generic_alarm:
    name: Algemeen alarm
  alarm_reset_alarm:
    name: Reset alarn
    icon: mdi:autorenew
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Refridgerator door link quality status monitoring sensor
  ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: door_refrigerator_linkquality
    state_topic: "zigbee2mqtt/aqara_refrigerator_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  ## Motion sensor office link quality status monitoring sensor
  ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: motion_office_linkquality
    state_topic: "zigbee2mqtt/mijia_office_motion"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Future use
  ##-----------------------------------------------------------------------------------------------
  # ## Freezer door link quality status monitoring sensor
  # - platform: "mqtt"
  #   name: door_freezer_linkquality
  #   state_topic: "zigbee2mqtt/aqara_freezer_door"
  #   availability_topic: "zigbee2mqtt/bridge/state"
  #   unit_of_measurement: "-"
  #   value_template: "{{ value_json.linkquality }}"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------

  ## Sensor alarm status Water meter
  ## Source: MQTT
  - platform: "mqtt"
    name: alert_water_meter
    state_topic: "home/alert/water_meter_update"
    value_template: "{{ value_json.device }}"
    json_attributes_topic: "home/alert/water_meter_update"

###############################################################################
#  Groups
###############################################################################

###############################################################################
#  Automations
###############################################################################

###############################################################################
#  Templates
###############################################################################

###############################################################################
#  Scripts
###############################################################################

###############################################################################
#  Timers
###############################################################################