## Package file for Home Assistant, used for presence  
## Type: Home Assistant yaml file
## Date added: 2019-11-17
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ## Timers
    timer.light_hallway:
      friendly_name: Halletje

###############################################################################
##  Entities
###############################################################################

## Added V0.4.0
input_boolean:
  light_hallway:
    name: Verlichting halletje
    icon: mdi:lightbulb

## Added V0.3.0
input_text:
  light_hallway_short_timer:
    name: Halletje timer kort (min)
    initial: 2
    min: 1
    max: 60
  light_hallway_long_timer:
    name: Halletje timer lang (min)
    initial: 5
    min: 1
    max: 60

###############################################################################
##  Groups
###############################################################################
group:
  light_hallway:
    name: Verlichting halletje
    entities:
      - switch.habridge_hallwaylight
      - input_boolean.light_hallway

###############################################################################
##  Automations
###############################################################################
automation:
  ## Added V0.3.0
  ## Test min and max settings on long hallwaylight timer input 
  - alias: "Light - Validate hallway light long timer"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_text.light_hallway_long_timer
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.light_hallway_long_timer
          value: >
            {% if (states('input_text.light_hallway_long_timer')|int) > 60 %}
              60
            {% elif (states('input_text.light_hallway_long_timer')|int) < 1 %}
              1
            {% else %}
              {{ states('input_text.light_hallway_long_timer')|int }}
            {% endif %}

  ## Added V0.3.0
  ## Test min and max settings on short hallwaylight timer input 
  - alias: "Light - Validate hallway light short timer"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_text.light_hallway_short_timer
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.light_hallway_short_timer
          value: >
            {% if (states('input_text.light_hallway_short_timer')|int) > 60 %}
              60
            {% elif (states('input_text.light_hallway_short_timer')|int) < 1 %}
              1
            {% else %}
              {{ states('input_text.light_hallway_short_timer')|int }}
            {% endif %}

  ## Switch on hallway light when someone arrives home
  - alias: "Light hallway on at home coming"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.door_front_door
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.light_porch
          state: "on"
        - condition: sun
          after: sunset
          after_offset: "00:15:00"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.light_hallway
      - service: timer.start
        data_template:
          entity_id: timer.light_hallway
          duration: "00:{{ states('input_text.light_hallway_short_timer')|int}}:00"
  ## Switch off hallway light based on timer
  - alias: "Light hallway xx minutes after trigger off"
    initial_state: "on"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.light_hallway
    condition:
    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.light_hallway
  
  ## Added V0.4.0
  ## Switch hallway light on and off
  - alias: "Light hallway toggle"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
        - switch.habridge_hallwaylight
        - input_boolean.light_hallway
    action:
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: input_boolean.domoticz_light_hallway
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: group.light_hallway

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################


###############################################################################
##  Timers
###############################################################################

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################


###############################################################################
##  Timers
###############################################################################
timer:
  light_hallway: