## Package file for Home Assistant, used for miscellaneous configs
## Type: Home Assistant yaml file
## Date added: 2019-11-06
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## outdoor environment
    ## Source: Home Assistant
    sun.sun:
      friendly_name: Dag/Nacht
    ## ZigBeee2MQTT Switch Outlet 1
    ## Source IKEA Tradfri E1603/E1702 ZigBee
    switch.switch_outlet_1:
      friendly_name: Outlet 1 (Tradfri)
    sensor.switch_outlet_1_linkquality:
      friendly_name:  Outlet 1 (link quality)
    binary_sensor.switch_outlet_1_update:
      friendly_name:  Outlet 1 (Update available)
    ## ZigBeee2MQTT Switch Outlet 2
    ## Source IKEA Tradfri E1603/E1702 ZigBee
    switch.switch_outlet_2:
      friendly_name: Outlet 2 (Tradfri)
    sensor.switch_outlet_2_linkquality:
      friendly_name:  Outlet 2 (link quality)
    binary_sensor.switch_outlet_2_update:
      friendly_name:  Outlet 2 (Update available)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Test
    ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Definition of workdays with the workday sensor
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri, sat]
    excludes: [sun]
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Test
  ##-----------------------------------------------------------------------------------------------
  - platform: "mqtt"
    name: switch_outlet_1_update
    state_topic: "zigbee2mqtt/outlet_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.update_available}}"
  - platform: "mqtt"
    name: switch_outlet_2_update
    state_topic: "zigbee2mqtt/outlet_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.update_available}}"

input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Holiday mode toggle switch, used for setting when on holiday 
  mode_holiday:
    name: Vakantie mode aan
    icon: mdi:toggle-switch
  ## Christmas mode toggle switch, used for setting the holiday season mode on 
  mode_christmas:
    name: Kerst periode mode
    icon: mdi:toggle-switch
  ## Lightlevel mode toggle switch, used for setting indoor lightlevels based on light sensor(s)
  ## on = dark, off = day light
  mode_dark_indoor:
    name: Licht level binnen
    icon: mdi:theme-light-dark
  ## Light lele mode toggle switch, used for setting outdoor light levels based on light sensor(s)
  ## on = dark, off = day light
  mode_dark_outdoor:
    name: Licht level buiten
    icon: mdi:theme-light-dark
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Test
  ##-----------------------------------------------------------------------------------------------
  ## Test wake-up light for master bedroom
  wakeup_mb_enabled:
    name: "Wake-up lights"
    initial: on
    icon: mdi:theme-light-dark
  wakeup_mb_weekday_enabled:
    name: "Wake-up op werkdagen"
    # initial: on
    icon: mdi:calendar-blank
  wakeup_mb_saturday_enabled:
    name: "Wake-up op zaterdag"
    # initial: off
    icon: mdi:calendar-blank
  wakeup_mb_sunday_enabled:
    name: "Wake-up op zondag"
    # initial: off
    icon: mdi:calendar-blank

  ## Test scenario switches
  scene_bed_time:
    name: "Bed tijd"
    initial: off
    icon: mdi:sleep
  scene_leaving:
    name: "Vertrekken"
    initial: off
    icon: mdi:home-export-outline
  scene_wakeup:
    name: "Wakker worden"
    initial: off
    icon: mdi:home-outline

input_datetime:
  ##-----------------------------------------------------------------------------------------------
  ##input_datetime - Test
  ##-----------------------------------------------------------------------------------------------
  ## Test wake-up light for master bedroom
  wakeup_time_mb_weekday:
    name: "Start licht weekdag"
    has_time: true
    has_date: false
    initial: "07:00"
  wakeup_time_mb_saturday:
    name: "Start licht zaterdag"
    has_time: true
    has_date: false
    initial: "06:45"
  wakeup_time_mb_sunday:
    name: "Start licht zondag"
    has_time: true
    has_date: false
    initial: "08:00"

input_select:
  ##-----------------------------------------------------------------------------------------------
  ##input_select - Test
  ##-----------------------------------------------------------------------------------------------
  ## Current house state - used for house state indicator (UI mainly)
  mode_house_state:
    name: "Huis status"
    options:
      - "Weg"
      - "Wakker"
      - "Slaapt"
      - "Lang weg"
      - "Vakantie"

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Season sensor (astronomical)
  ## Source: Home assistant
  - platform: season
    type: astronomical
  - platform: template
    sensors:
      ## Sunset
      ## Source: template sensor
      time_sunset:
        value_template: "{% set timestamp = as_timestamp(state_attr('sun.sun','next_setting')) | timestamp_custom('%H:%M') %} {{ timestamp }}"
        unit_of_measurement: "PM"
      ## Sunrise
      ## Source: template sensor
      time_sunrise:
        value_template: "{% set timestamp = as_timestamp(state_attr('sun.sun','next_rising')) | timestamp_custom('%H:%M') %} {{ timestamp }}"
        unit_of_measurement: "AM"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Test
  ##-----------------------------------------------------------------------------------------------
  ## Link quality outlet 1 (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: switch_outlet_1_linkquality
    state_topic: "zigbee2mqtt/tradfri_outlet_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
  ## Link quality outlet 2 (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: switch_outlet_2_linkquality
    state_topic: "zigbee2mqtt/tradfri_outlet_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"

switch:
  ##-----------------------------------------------------------------------------------------------
  ## switches - Active
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switches - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switches - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switches - Test
  ##-----------------------------------------------------------------------------------------------
  ## Switch outlet 1 (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: switch_outlet_1
    state_topic: "zigbee2mqtt/tradfri_outlet_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_outlet_1/set"
  ## Switch outlet 2 (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: switch_outlet_2
    state_topic: "zigbee2mqtt/tradfri_outlet_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_outlet_2/set"

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################