## Package file for Zigbee2mqtt control from Home Assistant
## Type: Home Assistant yaml file
## Date added: 2019-11-11
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
##-----------------------------------------------------------------------------------------------
## Customizations - Active
##-----------------------------------------------------------------------------------------------
    ## Permit join timers Zigbee2mqtt
    timer.zigbee2mqtt_permit_join:
      friendly_name: Resterende tijd Zigbee joinen toegestaan
##-----------------------------------------------------------------------------------------------
## Customizations - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## Customizations - Obsolete
##-----------------------------------------------------------------------------------------------


###############################################################################
##  Entities
###############################################################################
input_boolean:
##-----------------------------------------------------------------------------------------------
## input_boolean - Active
##-----------------------------------------------------------------------------------------------
  ## Input boolean for enabling/disabling joining
  zigbee2mqtt_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
##-----------------------------------------------------------------------------------------------
## input_boolean - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
##input_boolean - Obsolete
##-----------------------------------------------------------------------------------------------

input_select:
##-----------------------------------------------------------------------------------------------
## input_select - Active
##-----------------------------------------------------------------------------------------------
  ## Input select for Zigbee2mqtt debug level
  zigbee2mqtt_log_level_state:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted
##-----------------------------------------------------------------------------------------------
## input_select - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## input_select - Obsolete
##-----------------------------------------------------------------------------------------------

sensor:
##-----------------------------------------------------------------------------------------------
## sensors - Active
##-----------------------------------------------------------------------------------------------
  ## Sensor for monitoring the Zigbee2mqtt bridge state
  - platform: mqtt
    name: Zigbee2mqtt Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------

switch:
##-----------------------------------------------------------------------------------------------
## switches - Active
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## switches - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## switches - Obsolete
##-----------------------------------------------------------------------------------------------
  ## Switch for enabling joining
  - platform: mqtt
    name: "Zigbee2mqtt Main join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

###############################################################################
##  Groups
###############################################################################


###############################################################################
##  Automations
###############################################################################
automation:
##-----------------------------------------------------------------------------------------------
## automations - Active
##-----------------------------------------------------------------------------------------------
  - alias: "Zigbee2mqtt - Log Level"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_select.zigbee2mqtt_log_level_state
        to: debug
      - platform: state
        entity_id: input_select.zigbee2mqtt_log_level_state
        to: warn
      - platform: state
        entity_id: input_select.zigbee2mqtt_log_level_state
        to: error
      - platform: state
        entity_id: input_select.zigbee2mqtt_log_level_state
        to: info
    action:
      - service: mqtt.publish
        data:
          payload_template: "{{ states('input_select.zigbee2mqtt_log_level_state') }}"
          topic: zigbee2mqtt/bridge/config/log_level

  - id: enable_zigbee_join
    alias: "Zigbee2mqtt - Enable Zigbee joining"
    trigger:
      platform: state
      entity_id: input_boolean.zigbee2mqtt_permit_join
      to: "on"
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: "true"
    - service: timer.start
      data:
        entity_id: timer.zigbee2mqtt_permit_join

  - id: disable_zigbee_join
    alias: "Zigbee2mqtt - Disable Zigbee joining"
    trigger:
    - entity_id: input_boolean.zigbee2mqtt_permit_join
      platform: state
      to: "off"
    action:
    - data:
        payload: "false"
        topic: zigbee2mqtt/bridge/config/permit_join
      service: mqtt.publish
    - data:
        entity_id: timer.zigbee2mqtt_permit_join
      service: timer.cancel

  - id: disable_zigbee_join_timer
    alias: "Zigbee2mqtt - Disable Zigbee joining by timer"
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee2mqtt_permit_join
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: "false"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.zigbee2mqtt_permit_join
##-----------------------------------------------------------------------------------------------
## automations - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## automations - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################


###############################################################################
##  Timers
###############################################################################
timer:
##-----------------------------------------------------------------------------------------------
## timers - Active
##-----------------------------------------------------------------------------------------------
  ## Timer for joining time remaining (120 sec = 2 min)
  zigbee2mqtt_permit_join:
    name: Resterende tijd Zigbee joinen toegestaan
    duration: 120
##-----------------------------------------------------------------------------------------------
## timers - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## timers - Obsolete
##-----------------------------------------------------------------------------------------------