## Package file for Home Assistant, used for the Livingroom
## Type: Home Assistant yaml file
## Date added: 2019-03-10
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ## ZigBeee2MQTT Switches
    switch.tradfri_media_switch:
      friendly_name: Entertainment
    switch.tradfri_high_cabinets_switch:
      friendly_name: Verlichting hoge kasten (Tradfri)
    ## Scripts
    script.light_livingroom_on:
      icon: mdi:lightbulb
    script.light_livingroom_off:
      icon: mdi:lightbulb
    ## Timers
    timer.switch_christmastree_off:
      friendly_name: Kerstboom uitschakelvertraging
    timer.switch_christmastree_on:
      friendly_name: Kerstboom inschakelvertraging
    timer.light_high_cabinets_off:
      friendly_name: Hoge kasten uitschakelvertraging
    timer.light_high_cabinets_on:
      friendly_name: Hoge kasten inschakelvertraging 

# logger:
#   default: info
#   logs:
#     homeassistant.components.script: debug

###############################################################################
##  Entities
###############################################################################
input_boolean:
  ## Living roon light input
  ## Used in multiple automations and scripts
  livingroom_lights:
    name: Verlichting woonkamer
  ## Status of lighting in the livingroom used to see if lighitng is on 
  ## several automations depend on this
  livingroom_lights_status:
    name: Status wwoonkamer lampen
  ## Added V0.14.0
  ## Christmas tree switch
  ## Used in multiple automations and scripts
  christmastree:
    name: Kertstboom
    icon: mdi:pine-tree
  ## Barlight switch
  ## Used in multiple automations and scripts
  barlight:
    name: Verlichting bar
    icon: mdi:lightbulb
  ## High cabinets switch
  ## Used in multiple automations and scripts
  highcabinets:
    name: Verlichting hoge kasten (KaKu)
    icon: mdi:lightbulb

switch:
  ## Switch for high cabinets (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: tradfri_high_cabinets_switch
    state_topic: "zigbee2mqtt/tradfri_high_cabinets_switch"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_high_cabinets_switch/set"

sensor:
  ## Switch for high cabinets, sensor (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: tradfri_high_cabinets_switch
    state_topic: "zigbee2mqtt/tradfri_high_cabinets_switch"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

###############################################################################
##  Groups
###############################################################################
group:
  switch_christmastree:
    name: kerstboom
    entities:
      - switch.habridge_christmastree
      - input_boolean.christmastree
  light_bar:
    name: Verlichting bar
    entities:
      - switch.habridge_barlight
      - input_boolean.barlight
  light_high_cabinets:
    name: Verlichting hoge kasten (KaKu)
    entities:
      - switch.habridge_highcabinets
      - input_boolean.highcabinets

###############################################################################
##  Automations
###############################################################################
automation:
  ## ---------------------------------------------------------
  ## Automations using Amazon Alexa through HA-bridge commands
  ## ---------------------------------------------------------
  ## Switch on livingroom lights from HA-Bridge
  - alias: "Light livingroom on (HA Bridge)"
    initial_state: "on"
    trigger:
      platform: state
      entity_id:
        - binary_sensor.habridge_livingroom_lights_on
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.livingroom_lights
  ## Switch off livingroom lights from HA-Bridge
  - alias: "Light livingroom off (HA Bridge)"
    initial_state: "on"
    trigger:
      platform: state
      entity_id:
        - binary_sensor.habridge_livingroom_lights_off
      to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights

  ## Switch Christmas tree on and off
  - alias: "Switch christmas tree toggle"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
        - switch.habridge_christmastree
        - input_boolean.christmastree
    action:
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: input_boolean.domo_christmastree
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: group.switch_christmastree
  ## Switch Bar lights on and off
  - alias: "Light bar toggle"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
        - switch.habridge_barlight
        - input_boolean.barlight
    action:
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: input_boolean.domo_barlight
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: group.light_bar
  ## Switch lights high cabinets on and off
  - alias: "Light high cabinets toggle"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
        - switch.habridge_highcabinets
        - input_boolean.highcabinets
    action:
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: input_boolean.domo_highcabinets
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: group.light_high_cabinets

  ## Switch livingroom lights on and off
  - alias: "Light livingroom toggle"
    initial_state: "on"
    trigger:
      platform: state
      entity_id:
        - input_boolean.livingroom_lights
    action:
      - service_template: >-
          {{ 'script.light_livingroom_on' if is_state('input_boolean.livingroom_lights','on') else 'script.light_livingroom_off' }}

  ## Switch on kitchen cabinets light based on timer
  - alias: "Light high cabinets xx minutes after trigger on"
    initial_state: "on"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.light_high_cabinets_on
    condition:
    action:
    - service: homeassistant.turn_on
      entity_id: 
        - input_boolean.highcabinets
        # - switch.tradfri_high_cabinets_switch

  ## Switch off kitchen cabinets light based on timer
  - alias: "Light high cabinets xx minutes after trigger off"
    initial_state: "on"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.light_high_cabinets_off
    condition:
    action:
    - service: homeassistant.turn_off
      entity_id: 
        - input_boolean.highcabinets
        # - switch.tradfri_high_cabinets_switch

  ## Switch on christmas tree based on timer
  - alias: "Switch christmas tree xx minutes after trigger on"
    initial_state: "on"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.switch_christmastree_on
    condition:
    action:
    - service: homeassistant.turn_on
      entity_id: 
        - input_boolean.christmastree

  ##----------------------------------------------
  ## Test automations >> Remove ASAP after testing 
  ##----------------------------------------------

###############################################################################
##  Scripts
###############################################################################
script:
  light_livingroom_on:
    alias: Woonkamer licht aan script
    sequence:
      ## check if lights are currently off
      - condition: state
        entity_id: input_boolean.livingroom_lights_status
        state: "off"
      - service: homeassistant.turn_on
        entity_id:
          - input_boolean.livingroom_lights_status
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.highcabinets
      - service: script.light_hue_mode_change
      ## check if it is christmas time
      - condition: state
        entity_id: input_boolean.christmas_mode
        state: "on"
      ## Switch on the chritmas tree lights
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.christmastree
  light_livingroom_off:
    alias: Woonkamer licht uit script
    sequence:
      ## check if lights are currently on
      - condition: state
        entity_id: input_boolean.livingroom_lights_status
        state: "on"
      - service: homeassistant.turn_off
        entity_id:
          - input_boolean.livingroom_lights_status
      - service: timer.start
        data_template:
          entity_id: timer.light_high_cabinets_off
          duration: "00:01:00"
      - service: homeassistant.turn_off
        entity_id: 
          - light.woonkamer
      ## check if it is christmas time
      - condition: state
        entity_id: input_boolean.christmas_mode
        state: "on"
      - service: homeassistant.turn_off
        entity_id:
          - input_boolean.christmastree

###############################################################################
##  Timers
###############################################################################
timer:
## Timers high cabinets in the kitchen
  ## Switch on
  light_high_cabinets_on:
  ## Switch off
  light_high_cabinets_off:
## Timers controlling the christmas tree
  ## Switch on
  switch_christmastree_on:
  ## Switch off
  switch_christmastree_off: