## Package file for Home Assistant, used for presence  
## Type: Home Assistant yaml file
## Date added: 2019-11-17
## Last update: 2022-04-18 11:07
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Utilites cabinet door sensor
    ## Source: Xiaomi Aqara MCCGQ11LM
    binary_sensor.door_utilities_cabinet:
      friendly_name: Meterkast deur
    sensor.door_utilities_cabinet_linkquality:
      friendly_name: Meterkast (link quality)
    sensor.door_utilities_cabinet_battery:
      friendly_name: Batterij meterkast deur
    ## Dimmer 2nd floor bed room
    ## Source Lonsonho, QS-Zigbee-D02-TRIAC-LN
    light.light_utilities_cabinet:
      friendly_name: Verlichting meterkast
    sensor.light_utilities_cabinet_linkquality:
      friendly_name: Verlichting meterkast (link quality)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------
    ## Switch storage (Hallway light)
    ## Source: Xiaomi Aqara LLKZMK11LM
    switch.switch_hallway_light:
      friendly_name: Verlichting halletje

###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Utilities cabinet door
  ## Source: Xiaomi Aqara MCCGQ11LM
  - platform: "mqtt"
    name: door_utilities_cabinet
    state_topic: "zigbee2mqtt/utilities_cabinet_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ## Switch storage (Hallway light)
  ## Source Xiaomi Aqara LLKZMK11LM
  ## Commented as this device does not support /get for this parameter
  # - platform: "mqtt"
  #   name: switch_hallway_porch_interlock
  #   state_topic: "zigbee2mqtt/aqara_switch_hallway"
  #   availability_topic: "zigbee2mqtt/bridge/state"
  #   value_template: "{{ value_json.interlock }}"
  #   payload_on: true
  #   payload_off: false
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Test
  ##-----------------------------------------------------------------------------------------------

input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Button hallway lights
  ## Source: template
  light_hallway_button:
    name: Verlichting halletje
    icon: mdi:lightbulb
  ## Status monitoring hallway lights
  ## Source: template
  light_hallway:
    name: Verlichting halletje
    icon: mdi:lightbulb
  ## Door storage, location hallway-storage, will be replaced with real sensors in the future
  ## Source: Dummy switch
  dummy_hallway_storage_door:
    name: Tussendeur berging (dummy)
    icon: mdi:door-closed
  ## Door rest room, location hallway, will be replaced with real sensors in the future
  ## Source: Dummy switch
  dummy_rest_room_door:
    name: Toiletdeur (dummy)
    icon: mdi:door-closed
  ## Door hallway, location livingroom-hallway
  ## is defined in package-livingroom
    ## Storage door delayed open
  ## Source: template switch
  door_front_door_delayed:
    name: Voordeur vertraagd
    icon: mdi:door
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------
  # ## Door metering cabinet, location hallway, will be replaced with real sensors in the future
  # ## Source: Dummy switch
  # dummy_metering_cabinet_door:
  #   name: Meterkast deur (dummy)
  #   icon: mdi:door-closed

input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ## State indicator hallway lights
  ## Source: template 
  light_hallway:
    name: Verlichting halletje
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"

input_number:
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Active
  ##-----------------------------------------------------------------------------------------------
  ## Long timer hallway lights (used in Node_RED)
  ## Source: template
  light_hallway_long_timer:
    name: Halletje timer lang (min)
    initial: 5
    min: 1
    max: 30
    step: 1 
  ## Short timer hallway lights (used in Node_RED) 
  ## Source: template
  light_hallway_short_timer:
    name: Halletje timer kort (min)
    initial: 2
    min: 1
    max: 30
    step: 1
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Obsolete
  ##-----------------------------------------------------------------------------------------------

light:
  ##-----------------------------------------------------------------------------------------------
  ## lights - Active
  ##-----------------------------------------------------------------------------------------------
  ## Dimmer utilities cabinet
  ## Source Tradfri, ICPSHC24-10EU-IL-1
  - platform: "mqtt"
    name: light_utilities_cabinet
    state_topic: "zigbee2mqtt/utilities_cabinet_light"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: false
    xy: false
    hs: false
    schema: "json"
    command_topic: "zigbee2mqtt/utilities_cabinet_light/set"
    brightness_scale: 254
    effect: false
  ##-----------------------------------------------------------------------------------------------
  ## lights - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## lights - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## lights - Test
  ##-----------------------------------------------------------------------------------------------


sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Active
  ##-----------------------------------------------------------------------------------------------
    ##Hallway light switch 
  ## Source: Moes MS-104Z - ZigBee
  - platform: "mqtt"
    name: switch_hallway_light_linkquality
    state_topic: "zigbee2mqtt/moes_hallway_light"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.linkquality }}"
    unit_of_measurement: "lqi"
    icon: "mdi:signal"

  ## Dimmer utilities cabinet
  ## Source Tradfri, ICPSHC24-10EU-IL-1
  - platform: "mqtt"
    name: light_utilities_cabinet_linkquality
    state_topic: "zigbee2mqtt/utilities_cabinet_light"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
    icon: "mdi:signal"

  ## Utilities cabinet door sensor
  ## Source: Xiaomi Aqara MCCGQ11LM
  - platform: "mqtt"
    name: door_utilities_cabinet_linkquality
    state_topic: "zigbee2mqtt/utilities_cabinet_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    expire_after: 21600
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: door_utilities_cabinet_battery
    state_topic: "zigbee2mqtt/utilities_cabinet_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    expire_after: 21600
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Test
  ##-----------------------------------------------------------------------------------------------

switch:
  ##-----------------------------------------------------------------------------------------------
  ## switch - Active
  ##-----------------------------------------------------------------------------------------------
  ## Hallway light switch 
  ## Source: Moes MS-104Z - ZigBee
  - platform: "mqtt"
    name: switch_hallway_light
    state_topic: "zigbee2mqtt/moes_hallway_light"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/moes_hallway_light/set"
  ##-----------------------------------------------------------------------------------------------
  ## switch - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switch - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switch - Test
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################