## Package file for Home Assistant, used for environment
## Type: Home Assistant yaml file
## Date added: 2019-11-10
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
###############################################################################
#  Entities
###############################################################################
###############################################################################
##  Groups
###############################################################################
###############################################################################
##  Automations
###############################################################################
###############################################################################
##  Templates
###############################################################################
###############################################################################
##  Scripts
###############################################################################
###############################################################################
##  Timers
###############################################################################