## Package file for Home Assistant, used for the Livingroom
## Type: Home Assistant yaml file
## Date added: 2019-03-10
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Test
    ##-----------------------------------------------------------------------------------------------
    ## ZigBeee2MQTT Switch high cabinets
    ## Source SilverCrest,Lidl HG06337 ZigBee
    switch.switch_high_cabinets:
      friendly_name: High cabinets (SilverCrest)
    sensor.switch_high_cabinets_linkquality:
      friendly_name: High cabinets (link quality)

    ## ZigBeee2MQTT Switch christmas tree
    ## Source SilverCrest,Lidl HG06337 ZigBee
    switch.switch_christmas_tree:
      friendly_name: High cabinets (SilverCrest)
    sensor.switch_christmas_tree_linkquality:
      friendly_name: High cabinets (link quality)

###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Active
  ##-----------------------------------------------------------------------------------------------
  - platform: template
    sensors:
      light_livingroom_all:
        friendly_name: Alle verlichting woonkamer
        value_template: >-
          {{ is_state('input_boolean.light_high_cabinets','on')
            and is_state('input_boolean.light_livingroom_button','on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/lightbulb48_' ~ states('binary_sensor.light_livingroom_all') ~ '.png' }}
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensors - Test
  ##-----------------------------------------------------------------------------------------------

input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Button livingroom Hue lights
  ## Source: template
  light_livingroom_button:
    name: Verlichting woonkamer
    icon: mdi:lightbulb
  ## Button livingroom bar lights
  ## Source: template
  light_bar_button:
    name: Verlichting bar
    icon: mdi:lightbulb
  ## Status monitoring livingroom Hue lights
  ## Source: template
  light_livingroom:
    name: Verlichting woonkamer
    icon: mdi:lightbulb
  ## Button livingroom high cabinets
  ## Source: template
  light_high_cabinets:
    name: Verlichting hoge kasten (KaKu)
    icon: mdi:lightbulb
  ## Button livingroom christmas tree
  ## Source: template
  switch_christmas_tree:
    name: Kerstboom
    icon: mdi:pine-tree
  ## Button livingroom small christmas tree
  ## Source: template
  switch_small_christmas_tree:
    name: Kleine kerstboom
    icon: mdi:pine-tree
  ## Status monitoring livingroom bar lights
  ## Source: template
  light_bar:
    name: Verlichting bar
    icon: mdi:lightbulb

  ## Button all livingroom lights
  ## Source: template
  light_livingroom_all:
    name: Alle verlichting woonkamer
    icon: mdi:lightbulb

  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------
  # ## Button livingroom high cabinets
  # ## Source: template
  # light_high_cabinets_button:
  #   name: Button hoge kasten
  #   icon: mdi:lightbulb
  # ## Button livingroom christmas tree
  # ## Source: template
  # switch_christmas_tree_button:
  #   name: Kerstboom
  #   icon: mdi:pine-tree

input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ## Mode selector for the lights in the livingroom.
  ## Used for the modes the light can be set to from media center
  light_livingroom_mode:
    name: Verlichtsmode Woonkamer
    options:
      - Normaal
      - Video
    initial: Normaal
    icon: mdi:lightbulb
  ## Selector for the scenes for the Hue lighting
  light_livingroom_scene:
    name: Nieuwe hue scene
    icon: mdi:lightbulb
    options:
      - Normaal
      - Ontspannen
      - Lezen
      - Concentreren
      - Schoonmaken
      - Gedimd
      - Energie
      - Helder
      - Nachtlampje
      - Video
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ## State indicator livingroom hue lights
  ## Source: template 
  light_livingroom:
    name: Verlichting woonkamer
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"
  ## State indicator livingroom high cabinets
  ## Source: template
  light_high_cabinets:
    name: Hoge kasten Status
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"
  ## State indicator livingroom christmas tree
  ## Source: template
  switch_christmas_tree:
    name: Kerstboom
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"
  ## State indicator livingroom small christmas tree
  ## Source: template
  switch_small_christmas_tree:
    name: Kleine kerstboom
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"

input_number:
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Active
  ##-----------------------------------------------------------------------------------------------
  ## Livingroom lights short timer (configurable from UI)
  ## Source: template
  light_livingroom_short_timer:
    name: Woonkamer
    initial: 0
    min: 0
    max: 10
    step: 1
  ## High cabinets short timer (configurable from UI)
  ## Source: template
  light_high_cabinets_short_timer:
    name: Verlichting bar
    initial: 1
    min: 0
    max: 10
    step: 1
  ## Christmas tree short timer (configurable from UI)
  ## Source: template
  ## not used, no timer
  light_christmas_tree_short_timer:
    name: Kerstboom
    initial: 0
    min: 0
    max: 10
    step: 1
  ## Livingroom slider for Hue lights dimming
  ## Source: template
  light_livingroom_dimmer:
    name: Verlichting woonkamer
    initial: 100
    min: 0
    max: 100
    step: 1
  ## Livingroom slider for bar lights dimming
  ## Source: template
  light_bar_dimmer:
    name: Verlichting bar
    initial: 100
    min: 0
    max: 100
    step: 1 
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Obsolete
  ##-----------------------------------------------------------------------------------------------

light:
  ##-----------------------------------------------------------------------------------------------
  ## light - Active
  ##-----------------------------------------------------------------------------------------------
  ## light groups for setting the Hue lights. Present itself as light.xxx 
  - platform: group
    name: Woonkamer Hue
    entities:  
      - light.lage_kast_links
      - light.lage_kast_rechts
      - light.staande_lamp_links
      - light.staande_lamp_rechts
  - platform: group
    name: light low cabinets
    entities:
      - light.lage_kast_links
      - light.lage_kast_rechts
  - platform: group
    name: light standing lights
    entities:
      - light.staande_lamp_links
      - light.staande_lamp_rechts
  ##-----------------------------------------------------------------------------------------------
  ## light - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## light - Obsolete
  ##-----------------------------------------------------------------------------------------------

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Link quality high cabinets
    ## Source SilverCrest,Lidl HG06337 ZigBee
  - platform: "mqtt"
    name: switch_high_cabinets_linkquality
    state_topic: "zigbee2mqtt/high_cabinets"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"

  ## Link quality christmas tree
    ## Source SilverCrest,Lidl HG06337 ZigBee
  - platform: "mqtt"
    name: switch_christmas_tree_linkquality
    state_topic: "zigbee2mqtt/high_cabinets"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Test
  ##-----------------------------------------------------------------------------------------------

switch:
  ##-----------------------------------------------------------------------------------------------
  ## switches - Active
  ##-----------------------------------------------------------------------------------------------
  ## Switch high cabinets
  ## Source SilverCrest,Lidl HG06337 ZigBee
  - platform: "mqtt"
    name: switch_high_cabinets
    state_topic: "zigbee2mqtt/high_cabinets"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/high_cabinets/set"

  ## Switch christmas tree
  ## Source SilverCrest,Lidl HG06337 ZigBee
  - platform: "mqtt"
    name: switch_christmas_tree
    state_topic: "zigbee2mqtt/christmas_tree"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/christmas_tree/set"
  ##-----------------------------------------------------------------------------------------------
  ## switches - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switches - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switches - Test
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################
