## Package file for Home Assistant, used for notifications
## Type: Home Assistant yaml file
## Date added: 2019-11-04
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################

## Telegram bot settings
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret ralph_telegram_chat_id
      - !secret anneke_telegram_chat_id

## Notifier services
notify:
  - name: prowl_ralph
    platform: prowl
    api_key: !secret prowl_api_key
  - name: pushsafer
    platform: pushsafer
    private_key: !secret pushsafer_api_key
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: telegram_ralph
    platform: telegram
    chat_id: !secret ralph_telegram_chat_id
  - name: telegram_anneke
    platform: telegram
    chat_id: !secret anneke_telegram_chat_id

  - name: telegram_test
    platform: telegram
    chat_id: !secret ralph_telegram_chat_id

###############################################################################
##  Entities
###############################################################################
input_boolean: 
  text_notifications:
    name: Tekst notificaties toestaan
    icon: mdi:toggle-switch
    initial: on

###############################################################################
## Groups
###############################################################################
# group:
#   enable_scripts:
#     name: Scripts aan/uit
#     entities:
#       - input_boolean.text_notifications

###############################################################################
##  Automations
###############################################################################
automation:
  - alias: "Telegram bot reactie op keyboard"
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: "/remove"
    action:
      - service: telegram_bot.delete_message
        data_template:
          message_id: "{{ trigger.event.data.message.message_id }}"
          chat_id: !secret ralph_telegram_chat_id

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################
script:
## Prowl:
## Script to send notifications to a Prowl. Syntax:
## action:
##   service:  script.notify_prowl
##   data_template:
##     value1: "Startup: Home Assistant is Up and Running!"
##     value2: ""
##     value3: "{{ trigger.to_state.state }}"
##     priority: number
##     who: "name of the addressee", should match the selection in the list below. 
##          Defaults to "ralph"
##
## Prowl priority: An integer value ranging [-2, 2] representing:
## -2: Very Low
## -1: Moderate
##  0: Normal
##  1: High
##  2: Emergency
##
## Dependancies:
##   input_boolean.text_notifications

  notify_prowl:
    alias: Prowl notificaties 
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: "on"
      - service_template: >
            {% if who == 'ralph' %}
              notify.prowl_ralph
            {% elif who == 'anneke' %}
              notify.prowl_ralph
            {% elif who == 'kimbery' %}
              notify.prowl_ralph
            {% else %}
              notify.prowl_ralph
            {% endif %}
        data_template:
          message: "{{ value1 }} {{ value2 }} {{ value3 }}"
          title: "Melding"
          data:
            priority: "{{ prio }}"

## Pushbullet:
## Script to send notifications to Pushbullet. Syntax:
##   service:  script.notify_pushbullet
##   data_template:
##     value1: "Startup: Home Assistant is Up and Running!"
##     value2: ""
##     value3: "{{ trigger.to_state.state }}"
##     priority: number
##     who: "name of the addressee", should match the selection in the list below. 
##          Defaults to "ralph"
##
## Dependancies:
##   input_boolean.text_notifications

  notify_pushbullet:
    alias: Pushbullet notfications
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: "on"
      - service: notify.pushbullet
        data_template:
          title: "{{ title }}"
          message: "{{ value1 }} {{ value2 }} {{ value3 }}"

## Telegram:
## Script to send notifications to Pushbullet. Syntax:
##   service:  script.notify_pushbullet
##   data_template:
##     value1: "Startup: Home Assistant is Up and Running!"
##     value2: ""
##     value3: "{{ trigger.to_state.state }}"
##     priority: number
##
## Dependancies:
##   input_boolean.text_notifications
  notify_telegram_test:
    alias: Telegram notifications Ralph 
    sequence:
      - service: notify.telegram_test
        data_template:
          title: "Test"
          message: "Hi Ralph!"
          data:
            inline_keyboard:
              - 'Verwijder:/remove, OK:/ok'

  notify_telegram_ralph:
    alias: Telegram notifications Ralph
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: "on"
      - service: notify.telegram_ralph
        data_template:
          title: "{{ title }}"
          message: "Hi Ralph. {{ value1 }}{{ value2 }}{{ value3 }}"

  notify_telegram_anneke:
    alias: Telegram notifications Anneke
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: "on"
      - service: notify.telegram_anneke
        data_template:
          title: "{{ title }}"
          message: "Hi Anneke. {{ value1 }}{{ value2 }}{{ value3 }}"

  notify_telegram_ralph_and_anneke:
    alias: Telegram notifications ralph en Anneke
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: "on"
      - service: notify.telegram_anneke
        data_template:
          title: "{{ title }}"
          message: "Hi Anneke. {{ value1 }}{{ value2 }}{{ value3 }}"
      - delay: 
          milliseconds: 100
      - service: notify.telegram_ralph
        data_template:
          title: "{{ title }}"
          message: "Hi Ralph. {{ value1 }}{{ value2 }}{{ value3 }}"
###############################################################################
##  Timers
###############################################################################

