## Package file for Home Assistant, used for hardware monitoring
## Type: Home Assistant yaml file
## Date added: 2020-01-12
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Home server HDD
    ## Source: Domoticz via MQTT
    sensor.server_homeserver_hdd:
      friendly_name: Homerserver HDD
    ## Home server HDD boot
    ## Source: Domoticz via MQTT
    sensor.server_homeserver_hdd_boot:
      friendly_name: Homerserver HDD boot
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
sensor:
##-----------------------------------------------------------------------------------------------
## sensors - Active
##-----------------------------------------------------------------------------------------------
  ## Home server CPU temperature
  ## Source: template
  - platform: template
    sensors:
      server_homeserver_cpu_temp:
        value_template: >-
          {% set cpu_temp = states.sensor.glances_core_0_temp.state|int + 
            states.sensor.glances_core_1_temp.state|int %}
          {% set cpu_temp = cpu_temp/2|int %}
          {{ cpu_temp }}
        unit_of_measurement: "°C"
  ## Home server HDD boot
  ## Source: Domoticz via MQTT
  - platform: "mqtt"
    name: server_homeserver_hdd_boot
    state_topic: "home/server/homeserver/hdd_boot"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/hdd_boot"
    unit_of_measurement: "%"
  ## Home server HDD
  ## Source: Domoticz via MQTT
  - platform: "mqtt"
    name: server_homeserver_hdd
    state_topic: "home/server/homeserver/hdd"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/hdd"
    unit_of_measurement: "%"
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------
##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################