## Package file for Home Assistant, used for zones
## Type: Home Assistant yaml file
## Date added: 2019-01-14
## Author: R.Bisschops

###############################################################################
##                              Homeassistant settings
###############################################################################
homeassistant:
  customize:
##-----------------------------------------------------------------------------------------------
## Customizations - Active
##-----------------------------------------------------------------------------------------------
    zone.home:
      friendly_name: Thuis
    zone.cgi_rotterdam:
      friendly_name: CGI Rotterdam
    zone.cgi_maastricht:
      friendly_name: CGI Maastricht
    zone.cgi_eindhoven:
      friendly_name: CGI Eindhoven
    zone.cgi_arnhem:
      friendly_name: CGI Arnhem
    zone.cgi_groningen:
      friendly_name: CGI Groningen
##-----------------------------------------------------------------------------------------------
## Customizations - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## Customizations - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##                              Entities
###############################################################################
zone:
##-----------------------------------------------------------------------------------------------
## Zones - Active
##-----------------------------------------------------------------------------------------------
  ## Override for the default home zone
  - name: home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 70
    icon: mdi:home
  - name: CGI Rotterdam
    latitude: !secret latitude_cgi_rotterdam
    longitude: !secret longitude_cgi_rotterdam
    radius: 65
    icon: mdi:office-building
  - name: CGI Maastricht
    latitude: !secret latitude_cgi_maastricht
    longitude: !secret longitude_cgi_maastricht
    radius: 70
    icon: mdi:office-building
  - name: cgi_eindhoven
    latitude: !secret latitude_cgi_eindhoven
    longitude: !secret longitude_cgi_eindhoven
    radius: 70
    icon: mdi:office-building
  - name: cgi_arnhem
    latitude: !secret latitude_cgi_arnhem
    longitude: !secret longitude_cgi_arnhem
    radius: 70
    icon: mdi:office-building
  - name: cgi_groningen
    latitude: !secret latitude_cgi_groningen
    longitude: !secret longitude_cgi_groningen
    radius: 70
    icon: mdi:office-building
##-----------------------------------------------------------------------------------------------
## Zones - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## Zones - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##                               Groups
###############################################################################

###############################################################################
##                               Automations
###############################################################################

###############################################################################
##                              Templates
###############################################################################

###############################################################################
##                              Scripts
###############################################################################

###############################################################################
##                              Timers
###############################################################################