## Package file for Home Assistant, used for hardware monitoring
## Type: Home Assistant yaml file
## Date added: 2020-01-12
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
##-----------------------------------------------------------------------------------------------
## Customizations - Active
##-----------------------------------------------------------------------------------------------
  customize:
    ## Server sensors
    sensor.server_domoticz_cpu_temp:
      friendly_name: Domoticz server CPU temperatuur
    sensor.server_domoticz_cpu_usage:
      friendly_name: Domoticz server CPU gebruik
    sensor.server_domoticz_hdd:
      friendly_name: Domoticz server HDD
    sensor.server_domoticz_hdd_boot:
      friendly_name: Domoticz server HDD boot
    sensor.server_domoticz_memory_usage:
      friendly_name: Domoticz server geheugen gebruik
    sensor.server_domoticz_process_usage:
      friendly_name: Domoticz server gebruik processen
    sensor.server_homeserver_hdd:
      friendly_name: Homerserver HDD
    sensor.server_homeserver_hdd_boot:
      friendly_name: Homerserver HDD boot
##-----------------------------------------------------------------------------------------------
## Customizations - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## Customizations - Obsolete
##-----------------------------------------------------------------------------------------------
    ## Moved to integration Glances on HA
    sensor.server_homeserver_cpu_temp:
      friendly_name: Homerserver CPU temperatuur
    sensor.server_homeserver_cpu_usage:
      friendly_name: Homerserver CPU gebruik
    sensor.server_homeserver_process_usage:
      friendly_name: Homerserver gebruik processen
    sensor.server_homeserver_memory_usage:
      friendly_name: Homerserver HDD geheugen gebruik

###############################################################################
##  Entities
###############################################################################
sensor:
##-----------------------------------------------------------------------------------------------
## sensors - Active
##-----------------------------------------------------------------------------------------------
  ## Homeserver server hardware monitoring
  - platform: "mqtt"
    name: server_homeserver_hdd_boot
    state_topic: "home/server/homeserver/hdd_boot"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/hdd_boot"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_homeserver_hdd
    state_topic: "home/server/homeserver/hdd"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/hdd"
    unit_of_measurement: "%"
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------
  - platform: template
    sensors:
      server_homeserver_cpu_temp:
        value_template: >-
          {% set cpu_temp = states.sensor.glances_core_0_temp.state|int + 
            states.sensor.glances_core_1_temp.state|int +
            states.sensor.glances_core_2_temp.state|int +
            states.sensor.glances_core_3_temp.state|int %}
          {% set cpu_temp = cpu_temp/4|int %}
          {{ cpu_temp }}
        unit_of_measurement: "°C"
##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------
  ## Domoticz server hardware monitoring
  - platform: "mqtt"
    name: server_domoticz_memory_usage
    state_topic: "home/server/domoticz/mem_usage"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/domoticz/mem_usage"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_domoticz_hdd_boot
    state_topic: "home/server/domoticz/hdd_boot"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/domoticz/hdd_boot"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_domoticz_hdd
    state_topic: "home/server/domoticz/hdd"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/domoticz/hdd"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_domoticz_cpu_temp
    state_topic: "home/server/domoticz/cpu_temp"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/domoticz/cpu_temp"
    unit_of_measurement: "°C"
    device_class: "temperature"
  - platform: "mqtt"
    name: server_domoticz_cpu_usage
    state_topic: "home/server/domoticz/cpu_usage"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/domoticz/cpu_usage"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_domoticz_process_usage
    state_topic: "home/server/domoticz/process_usage"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/domoticz/process_usage"
    unit_of_measurement: "MB"
  - platform: "mqtt"
    name: server_homeserver_memory_usage
    state_topic: "home/server/homeserver/mem_usage"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/mem_usage"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_homeserver_cpu_usage
    state_topic: "home/server/homeserver/cpu_usage"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/cpu_usage"
    unit_of_measurement: "%"
  - platform: "mqtt"
    name: server_homeserver_process_usage
    state_topic: "home/server/homeserver/process_usage"
    value_template: "{{ value_json.usage|float }}"
    json_attributes_topic: "home/server/homeserver/process_usage"
    unit_of_measurement: "MB"

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################

