## Package file for Home Assistant, used for the storage area
## Type: Home Assistant yaml file
## Date added: 2019-11-17
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ## Sensors 
    sensor.vibration_mailbox:
      friendly_name: Brievenbus
    ## Timers
    timer.light_porch:
      friendly_name: Timer buitenlamp


###############################################################################
##  Entities
###############################################################################
input_boolean:
  porchlight:
    name: Buitenlamp
    icon: mdi:lightbulb

input_text:
  light_porch_long_timer:
    name: Buitenlamp timer lang (min)
    initial: 10
    min: 1
    max: 60
  light_porch_short_timer:
    name: Buitenlamp timer kort (min)
    initial: 5
    max: 60
    min: 1

sensor:
  ## Mailbox vibration sensor
  - platform: "mqtt"
    name: vibration_mailbox
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
  - platform: "mqtt"
    name: vibration_mailbox_all
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json }}"
  - platform: "mqtt"
    name: vibration_mailbox_linkquality
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

###############################################################################
##  Groups
###############################################################################
group:
  light_porch:
    name: Buitenlamp
    entities:
      - switch.habridge_porchlight
      - input_boolean.porchlight

###############################################################################
##  Automations
###############################################################################
automation:
  ## Test min and max settings on long porch light timer input 
  - alias: "Light - Validate porch light long timer"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_text.light_porch_long_timer
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.light_porch_long_timer
          value: >
            {% if (states('input_text.light_porch_long_timer')|int) > 60 %}
              60
            {% elif (states('input_text.light_porch_long_timer')|int) < 1 %}
              1
            {% else %}
              {{ states('input_text.light_porch_long_timer')|int }}
            {% endif %}

  ## Test min and max settings on short porch light timer input 
  - alias: "Light - Validate porch light short timer"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_text.light_porch_short_timer
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.light_porch_short_timer
          value: >
            {% if (states('input_text.light_porch_short_timer')|int) > 60 %}
              60
            {% elif (states('input_text.light_porch_short_timer')|int) < 1 %}
              1
            {% else %}
              {{ states('input_text.light_porch_short_timer')|int }}
            {% endif %}

  ## Switch on porch light when someone arrives home
  - alias: "Light porch on at home coming"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_select.presence_state_ralph, input_select.presence_state_anneke, input_select.presence_state_kimberly
        from: "Away"
        to: "Just Arrived"
      - platform: state
        entity_id: input_select.presence_state_ralph, input_select.presence_state_anneke, input_select.presence_state_kimberly
        from: "Extended Away"
        to: "Just Arrived"
    condition:  
      condition: or
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.porchlight
      - service: timer.start
        data_template:
          entity_id: timer.light_porch
          duration: "00:{{ states('input_text.light_porch_long_timer')|int }}:00"

  ## Switch off porchlight based on timer
  - alias: "Light porch xx minutes after trigger off"
    initial_state: "on"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.light_porch
    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.porchlight

  ## Switch Porch light on and off
  - alias: "Light Porch toggle"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: 
        - switch.habridge_porchlight
        - input_boolean.porchlight
    action:
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: input_boolean.domo_porchlight
      - service_template: >-
          {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
        entity_id: group.light_porch

  ## Actions to perform on mailbox motion
  - alias: "Vibration - Mail received"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: sensor.vibration_mailbox
      to: "vibration"
    action:
      - service_template: >
          {% if (is_state('input_select.presence_state_ralph', 'Home')) and (is_state('input_select.presence_state_anneke', 'Home'))  %}
            script.notify_telegram_ralph_and_anneke
          {% elif is_state('input_select.presence_state_ralph', 'Home') %}
            script.notify_telegram_ralph
          {% elif is_state('input_select.presence_state_anneke', 'Home') %}
            script.notify_telegram_anneke
          {% endif %}
        data_template:
          value1: "Er is post!"
          value2: " "
          value3: " "
          prio: -2

###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################


###############################################################################
##  Timers
###############################################################################
timer:
  light_porch:
  # wait:
