## Package file for Home Assistant, used for weather  
## Type: Home Assistant yaml file
## Date added: 2019-11-11
## Author: R.Bisschops

#################################################################################################
##  Homeassistant settings
#################################################################################################
weather:
##-----------------------------------------------------------------------------------------------
## Weather services - Active
##-----------------------------------------------------------------------------------------------
  - platform: buienradar

#################################################################################################
##  Entities
#################################################################################################
camera:
##-----------------------------------------------------------------------------------------------
## cameras - Active
##-----------------------------------------------------------------------------------------------
  ## Camera used for buienradar
  - platform: generic
    name: buienradar
    still_image_url: "https://api.buienradar.nl/image/1.0/RadarMapNL?w=256h=256"
##-----------------------------------------------------------------------------------------------
## cameras - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## cameras - Obsolete
##-----------------------------------------------------------------------------------------------

sensor:
##-----------------------------------------------------------------------------------------------
## sensors - Active
##-----------------------------------------------------------------------------------------------
  ## Buienradar
  - platform: buienradar
    timeframe: 5
    monitored_conditions:
      - stationname
      - conditioncode
      - condition
      - conditiondetailed
      - conditionexact    
      - symbol
      - humidity
      - temperature
      - groundtemperature
      - windspeed
      - windforce
      - winddirection
      - windazimuth
      - pressure
      - visibility
      - windgust
      - precipitation
      - irradiance
      ## Forecast conditions
      - precipitation_forecast_average
      - precipitation_forecast_total
      - rainchance_1d
      - rainchance_2d
      - rainchance_3d
      - rainchance_4d
      - rainchance_5d
      - sunchance_1d
      - sunchance_2d
      - sunchance_3d
      - sunchance_4d
      - sunchance_5d
      - symbol_1d
      - symbol_2d
      - symbol_3d
      - symbol_4d
      - symbol_5d
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------

#################################################################################################
##  Templates
#################################################################################################

#################################################################################################
##  Groups
#################################################################################################

#################################################################################################
##  Automations
#################################################################################################

#################################################################################################
##  Scripts
#################################################################################################

#################################################################################################
##  Timers
#################################################################################################