## Package file for Home Assistant, used for the 2nd floor bed room
## Type: Home Assistant yaml file
## Date added: 2021-01-03
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## ZigBeee2MQTT Switch high cabinets
    ## Source SilverCrest,Lidl HG06337 ZigBee
    light.light_room_kim:
      friendly_name: Verlichting kamer Kim
    sensor.light_room_kim_linkquality:
      friendly_name: Verlichting kamer Kim (link quality)
    sensor.button_room_kim:
      friendly_name: Verlichtings knop kamer Kim
    sensor.button_room_kim_battery:
      friendly_name: Verlichtings knop kamer Kim (batterij)
    sensor.button_room_kim_linkquality:
      friendly_name: Verlichtings knop kamer Kim (link quality)
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Test
    ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
light:
  ##-----------------------------------------------------------------------------------------------
  ## lights - Active
  ##-----------------------------------------------------------------------------------------------
  ## Switch 2nd floor bed room
  ## Source Lonsonho, QS-Zigbee-D02-TRIAC-LN
  - platform: "mqtt"
    name: light_room_kim
    state_topic: "zigbee2mqtt/lonsonho_dimmer_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: false
    xy: false
    hs: false
    schema: "json"
    command_topic: "zigbee2mqtt/lonsonho_dimmer_1/set"
    brightness_scale: 254
    effect: false
  ##-----------------------------------------------------------------------------------------------
  ## lights - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## lights - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## lights - Test
  ##-----------------------------------------------------------------------------------------------

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Switch 2nd floor bed room
  ## Source Lonsonho, QS-Zigbee-D02-TRIAC-LN
  - platform: "mqtt"
    name: light_room_kim_linkquality
    state_topic: "zigbee2mqtt/lonsonho_dimmer_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
    icon: "mdi:signal"
  ## Button 2nd floor bed room
  ## Xiaomi Mijia wireless switch, WXKG01LM
  - platform: "mqtt"
    name: button_room_kim
    state_topic: "zigbee2mqtt/aqara_bedroom_kim_button"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.action }}"
    icon: "mdi:gesture-double-tap"
  ## Button 2nd floor bed room
  ## Xiaomi Mijia wireless switch, WXKG01LM
  - platform: "mqtt"
    name: button_room_kim_battery
    state_topic: "zigbee2mqtt/aqara_bedroom_kim_button"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    value_template: "{{ value_json.battery }}"
    device_class: "battery"
  ## Button 2nd floor bed room
  ## Xiaomi Mijia wireless switch, WXKG01LM
  - platform: "mqtt"
    name: button_room_kim_linkquality
    state_topic: "zigbee2mqtt/aqara_bedroom_kim_button"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
    icon: "mdi:signal"
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Test
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################
