## Package file for Home Assistant, used for the storage area
## Type: Home Assistant yaml file
## Date added: 2019-11-17
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
##-----------------------------------------------------------------------------------------------
## Customizations - Active
##-----------------------------------------------------------------------------------------------
    ## Mailbox vibration sensor
    sensor.vibration_mailbox:
      friendly_name: Brievenbus
    sensor.vibration_mailbox_battery:
      friendly_name: Brievenbus (batterij)
    sensor.vibration_mailbox_linkquality:
      friendly_name: Brievenbus (link quality)
##-----------------------------------------------------------------------------------------------
## Customizations - Check
##-----------------------------------------------------------------------------------------------
    ## Mailbox vibration sensor
    sensor.vibration_mailbox_all:
      friendly_name: Brievenbus (compleet)
##-----------------------------------------------------------------------------------------------
## Customizations - Obsolete
##-----------------------------------------------------------------------------------------------
    ## Timers
    # timer.light_porch:
    #   friendly_name: Timer buitenlamp

###############################################################################
##  Entities
###############################################################################
input_boolean:
##-----------------------------------------------------------------------------------------------
## input_boolean - Active
##-----------------------------------------------------------------------------------------------
  ## Manual mode switches for things
  light_porch_button:
    name: Buitenlamp
    icon: mdi:lightbulb
  ## Status monitoring, only change state based in input from Node-RED
  light_porch:
    name: Buitenlamp
    icon: mdi:lightbulb
  ## Delayed storage door input, used for delaying vibration sensor alert
  door_storage_door_delayed:
    name: Berging deur vetraagd
    icon: mdi:door
##-----------------------------------------------------------------------------------------------
## input_boolean - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
##input_boolean - Obsolete
##-----------------------------------------------------------------------------------------------


##-----------------------------------------------------------------------------------------------
## Updated and changed entities - input_select
##-----------------------------------------------------------------------------------------------
input_select:
##-----------------------------------------------------------------------------------------------
## input_select - Active
##-----------------------------------------------------------------------------------------------
  ## State indicators for things
  light_porch:
    name: Buitenlamp
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"
##-----------------------------------------------------------------------------------------------
## input_select - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## input_select - Obsolete
##-----------------------------------------------------------------------------------------------


##-----------------------------------------------------------------------------------------------
## Updated and changed entities - input_number
##-----------------------------------------------------------------------------------------------
input_number:
##-----------------------------------------------------------------------------------------------
## input_number - Active
##-----------------------------------------------------------------------------------------------
  light_porch_long_timer:
    name: Buitenlamp timer lang (min)
    initial: 10
    min: 1
    max: 30
    step: 1 
  light_porch_short_timer:
    name: Buitenlamp timer kort (min)
    initial: 5
    min: 1
    max: 30
    step: 1
  light_porch_off_delay:
    name: Buitenlamp uit vertraging (sec)
    initial: 1
    min: 0
    max: 10
    step: 0.5
##-----------------------------------------------------------------------------------------------
## input_number - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## input_number - Obsolete
##-----------------------------------------------------------------------------------------------

sensor:
##-----------------------------------------------------------------------------------------------
## sensors - Active
##-----------------------------------------------------------------------------------------------
  ## Mailbox vibration sensor
  - platform: "mqtt"
    name: vibration_mailbox
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"
  - platform: "mqtt"
    name: vibration_mailbox_linkquality
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------
  - platform: "mqtt"
    name: vibration_mailbox_all
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json }}"
##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################
## Moved automations to Node-RED for test
# group:
#   light_porch:
#     name: Buitenlamp
#     entities:
#       # - switch.habridge_porchlight
#       - input_boolean.light_porch

###############################################################################
##  Automations
###############################################################################
automation:
##-----------------------------------------------------------------------------------------------
## automations - Active
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## automations - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## automations - Obsolete
##-----------------------------------------------------------------------------------------------
  ## Test min and max settings on long porch light timer input 
  ## Moved automations to Node-RED
  ## Replaced with input_number (slider)
  # - alias: "Light - Validate porch light long timer"
  #   initial_state: "on"
  #   trigger:
  #     - platform: state
  #       entity_id: input_text.light_porch_long_timer
  #   action:
  #     - service: input_text.set_value
  #       data_template:
  #         entity_id: input_text.light_porch_long_timer
  #         value: >
  #           {% if (states('input_text.light_porch_long_timer')|int) > 60 %}
  #             60
  #           {% elif (states('input_text.light_porch_long_timer')|int) < 1 %}
  #             1
  #           {% else %}
  #             {{ states('input_text.light_porch_long_timer')|int }}
  #           {% endif %}

  ## Test min and max settings on short porch light timer input 
  ## Moved automations to Node-RED
  ## Replaced with input_number (slider)
  # - alias: "Light - Validate porch light short timer"
  #   initial_state: "on"
  #   trigger:
  #     - platform: state
  #       entity_id: input_text.light_porch_short_timer
  #   action:
  #     - service: input_text.set_value
  #       data_template:
  #         entity_id: input_text.light_porch_short_timer
  #         value: >
  #           {% if (states('input_text.light_porch_short_timer')|int) > 60 %}
  #             60
  #           {% elif (states('input_text.light_porch_short_timer')|int) < 1 %}
  #             1
  #           {% else %}
  #             {{ states('input_text.light_porch_short_timer')|int }}
  #           {% endif %}

  ## Switch on porch light when someone arrives home
  ## Moved automations to Node-RED
  # - alias: "Light porch on at home coming"
  #   initial_state: "on"
  #   trigger:
  #     - platform: state
  #       entity_id: input_select.presence_ralph_bisschops, input_select.presence_anneke_bisschops, input_select.presence_kimberly_bisschops
  #       from: "Away"
  #       to: "Just Arrived"
  #     - platform: state
  #       entity_id: input_select.presence_ralph_bisschops, input_select.presence_anneke_bisschops, input_select.presence_kimberly_bisschops
  #       from: "Extended Away"
  #       to: "Just Arrived"
  #   condition:  
  #     condition: or
  #     conditions:
  #       - condition: sun
  #         after: sunset
  #       - condition: sun
  #         before: sunrise
  #   action:
  #     - service: homeassistant.turn_on
  #       entity_id: input_boolean.light_porch
  #     - service: timer.start
  #       data_template:
  #         entity_id: timer.light_porch
  #         duration: "00:{{ states('input_text.light_porch_long_timer')|int }}:00"

  ## Switch off porchlight based on timer
  ## Moved automations to Node-RED
  # - alias: "Light porch xx minutes after trigger off"
  #   initial_state: "on"
  #   trigger:
  #     platform: event
  #     event_type: timer.finished
  #     event_data:
  #       entity_id: timer.light_porch
  #   action:
  #   - service: homeassistant.turn_off
  #     entity_id: input_boolean.light_porch

  ## Switch Porch light on and off
  ## Moved automations to Node-RED for test
  # - alias: "Light Porch toggle"
  #   initial_state: "on"
  #   trigger:
  #     platform: state
  #     entity_id: 
  #       - switch.habridge_porchlight
  #       - input_boolean.light_porch
  #   action:
  #     - service_template: >-
  #         {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
  #       entity_id: input_boolean.domoticz_light_porch
  #     - service_template: >-
  #         {{ 'homeassistant.turn_on' if is_state(trigger.entity_id, 'on') else 'homeassistant.turn_off' }}
  #       entity_id: group.light_porch

  ## Actions to perform on mailbox motion
  ## Moved automations to Node-RED
  # - alias: "Vibration - Mail received"
  #   initial_state: "off"
  #   trigger:
  #     platform: state
  #     entity_id: sensor.vibration_mailbox
  #     to: "vibration"
  #   action:
  #     - service_template: >
  #         {% if (is_state('input_select.presence_ralph_bisschops', 'Home')) and (is_state('input_select.presence_anneke_bisschops', 'Home'))  %}
  #           script.notify_telegram_ralph_and_anneke
  #         {% elif is_state('input_select.presence_ralph_bisschops', 'Home') %}
  #           script.notify_telegram_ralph
  #         {% elif is_state('input_select.presence_anneke_bisschops', 'Home') %}
  #           script.notify_telegram_anneke
  #         {% endif %}
  #       data_template:
  #         value1: "Er is post!"
  #         value2: " "
  #         value3: " "
  #         prio: -2

  ## automationss for setting the slave storage door contact
  # Example remove after update
  # - alias: "Bergingdeur vetraagd dicht"
  #   description: "When storage door closes, delayed contact."
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.door_storage_door
  #   action:
  #     - choose:
  #         - conditions:
  #             - condition: state
  #               entity_id: binary_sensor.door_storage_door
  #               state: "on"
  #           sequence:
  #             - service: homeassistant.turn_on
  #               entity_id: input_boolean.door_storage_door_delayed
  #         - conditions:
  #             - condition: state
  #               entity_id: binary_sensor.button2
  #               state: "off"
  #           sequence:
  #             - delay: 
  #                 seconds: 10
  #             - service: homeassistant.turn_off
  #               entity_id: input_boolean.door_storage_door_delayed
  #       default:
  #         - service: homeassistant.turn_off
  #           entity_id: input_boolean.door_storage_door_delayed

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################
# timer:
##-----------------------------------------------------------------------------------------------
## timers - Active
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## timers - Check
##-----------------------------------------------------------------------------------------------

##-----------------------------------------------------------------------------------------------
## timers - Obsolete
##-----------------------------------------------------------------------------------------------
#   light_porch:
  # wait:
