## Package file for Home Assistant, used for all alarm sensors and
## associated automations and scripts
## Type: Home Assistant yaml file
## Date added: 2020-02-26
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
###############################################################################
#  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Alarm state, used for lovelace tab Home
  ## Source: template
  - platform: template
    sensors:
      alarm_generic_alarm:
        friendly_name: Algemeen alarm
        value_template: >-
          {{ is_state('input_boolean.alarm_generic_alarm', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/alarm48_' ~ states('input_boolean.alarm_generic_alarm') ~ '.png'}}
  ## Group door open sensors (monitors all outside doors)
  ## Source: template
  - platform: template
    sensors:
      door_all_doors:
        friendly_name: Alle deuren
        value_template: >-
          {{ is_state('binary_sensor.door_front_door_door_state', 'on')
            or is_state('binary_sensor.door_storage_door_door_state', 'on')
            or is_state('input_boolean.dummy_garden_door', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/door48_' ~ states('binary_sensor.door_all_doors') ~ '.png'}}
  ## Group window open sensors (monitors all windows)
  ## Source: template
  - platform: template
    sensors:
      door_all_windows:
        friendly_name: Alle ramen
        value_template: >-
          {{ is_state('input_boolean.dummy_groundfloor_front_window', 'on')
            or is_state('input_boolean.dummy_office_window', 'on')
            or is_state('input_boolean.dummy_side_room_window', 'on')
            or is_state('input_boolean.bedroom_window_l', 'on')
            or is_state('input_boolean.bedroom_window_r', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/window48_' ~ states('binary_sensor.door_all_windows') ~ '.png'}}
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------

input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Generic alarm input switch
  ## Source: Dummy
  alarm_generic_alarm:
    name: Algemeen alarm
  alarm_reset_alarm:
    name: Reset alarn
    icon: mdi:autorenew
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Obsolete
  ##-----------------------------------------------------------------------------------------------

  ## Sensor alarm status Water meter
  ## Source: MQTT
  - platform: "mqtt"
    name: alert_water_meter
    state_topic: "home/alert/water_meter_update"
    value_template: "{{ value_json.device }}"
    json_attributes_topic: "home/alert/water_meter_update"

###############################################################################
#  Groups
###############################################################################

###############################################################################
#  Automations
###############################################################################

###############################################################################
#  Templates
###############################################################################

###############################################################################
#  Scripts
###############################################################################

###############################################################################
#  Timers
###############################################################################