## Package file for Home Assistant, used for battery level monitoring
## Type: Home Assistant yaml file
## Date added: 2020-03-24
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Office environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_office_battery:
      friendly_name:  Batterij multisensor kantoor
    ## Livingroom environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_livingroom_battery:
      friendly_name:  Batterij multisensor woonkamer
    ## Bathroom environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_bathroom_battery:
      friendly_name:  Batterij multisensor badkamer
    ## Master bedroom environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_bedroom_battery:
      friendly_name:  Batterij multisensor slaapkamer
    ## 2nd fllor bedroom environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_kim_battery:
      friendly_name:  Batterij multisensor kamer Kim
    ## Restroom environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_toilet_battery:
      friendly_name:  Batterij multisensor toilet
    ## Storage environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_storage_battery:
      friendly_name:  Batterij multisensor berging
    ## Heatingroom environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_heating_room_battery:
      friendly_name: Batterij multisensor ketel ruimte
    ## 2nd floor hallway environment sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.environment_hallway_floor2_battery:
      friendly_name: Batterij multisensor overloop 2e verdieping
    ## Office light level sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.light_level_office_battery:
      friendly_name: Batterij licht sensor kantoor
    ## Grden light level sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.light_level_garden_battery:
      friendly_name: Batterij licht sensor tuin
    ## Refridgerator door sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.door_refrigerator_battery:
      friendly_name: Batterij koelkastdeur
    ## Office motion sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.motion_office_battery:
      friendly_name: Batterij bewegingssensor kantoor
    ## Mailbox vibration sensor - battery state
    ## Source: Xiaomi Aqara ZigBee
    sensor.vibration_mailbox_battery:
      friendly_name: Batterij brievenbus sensor

    ## Test environment sensor
    ## Source: Dummy
    sensor.environment_test_battery:
      friendly_name: Batterij test sensor

    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

###############################################################################
#  Entities
###############################################################################
sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensors - Active
  ##-----------------------------------------------------------------------------------------------
  ## Inhouse environment sensors
    ## Office environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_office_battery
    state_topic: "zigbee2mqtt/aqara_office_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Bathroom environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_bathroom_battery
    state_topic: "zigbee2mqtt/aqara_bathroom_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Master bedroom environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_bedroom_battery
    state_topic: "zigbee2mqtt/aqara_bedroom_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## 2nd floor bedroom environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_kim_battery
    state_topic: "zigbee2mqtt/aqara_kim_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Livingroom environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_livingroom_battery
    state_topic: "zigbee2mqtt/aqara_livingroom_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Restroom environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_toilet_battery
    state_topic: "zigbee2mqtt/aqara_toilet_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Storage environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_storage_battery
    state_topic: "zigbee2mqtt/aqara_storage_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Heating room environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_heating_room_battery
    state_topic: "zigbee2mqtt/aqara_heating_room_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## 2nd floor hallway environment sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: environment_hallway_floor2_battery
    state_topic: "zigbee2mqtt/aqara_hallway_floor2_env"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Office light level sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name:  light_level_office_battery
    state_topic: "zigbee2mqtt/light_sensor"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Tuin light level sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name:  light_level_garden_battery
    state_topic: "zigbee2mqtt/light_sensor_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Refridgerator door sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: door_refrigerator_battery
    state_topic: "zigbee2mqtt/aqara_refrigerator_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Office motion sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: motion_office_battery
    state_topic: "zigbee2mqtt/mijia_office_motion"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    ## Mailbox vibration sensor
    ## Source: Xiaomi Aqara ZigBee
  - platform: "mqtt"
    name: vibration_mailbox_battery
    state_topic: "zigbee2mqtt/aqara_mailbox"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
##-----------------------------------------------------------------------------------------------
## sensors - Check
##-----------------------------------------------------------------------------------------------
##-----------------------------------------------------------------------------------------------
## sensors - Obsolete
##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################