## Package file for Home Assistant, used for the garden
## Type: Home Assistant yaml file
## Date added: 2019-08-01
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    binary_sensor.switch_garden_interlock:
      friendly_name: Schakelaar tuin (interlock)
    sensor.switch_garden_power:
      friendly_name: Schakelaar tuin (verbruik)
    sensor.switch_garden_energy:
      friendly_name: Schakelaar tuin (energy)
    sensor.switch_garden_temperature:
      friendly_name: Schakelaar tuin (temperatuur)
    sensor.switch_garden_voltage:
      friendly_name: Schakelaar tuin (voltage)
    sensor.switch_garden_linkquality:
      friendly_name: Schakelaar tuin (link quality)
    switch.switch_garden_lights:
      friendly_name: Verlichting tuin
    switch.switch_garden_spare:
      friendly_name: Reserve tuin
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Test
    ##-----------------------------------------------------------------------------------------------
###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Switch garden
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_interlock
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.interlock }}"
    payload_on: true
    payload_off: false
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Test
  ##-----------------------------------------------------------------------------------------------

input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Button water ornament
  ## Source: template switch
  switch_water_ornament_button:
    name: Waterbollen
    icon: mdi:fountain
  ## Button sunscreen
  ## Source: template switch
  blinds_sunscreen_button:
    name: Zonnescherm
    icon: mdi:blinds 
  ## Status monitoring garden lights
  ## Source: template switch
  light_garden_lights:
    name: Tuin verlichting
    icon: mdi:lightbulb
  ## Status monitoring water ornament
  ## Source: template switch
  switch_water_ornament:
    name: Waterbollen
    icon: mdi:fountain
  ## Status monitoring sunscreen
  ## Source: template switch
  blinds_sunscreen:
    name: Zonnescherm
    icon: mdi:blinds
  ## Manual mode switch for the sunscreen
  ## Source: template switch
  blinds_sunscreen_manual:
    name: Zonnescherm handmatig
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------
  # light_garden_button:
  #   name: Tuin verlichting
  #   icon: mdi:lightbulb

input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ## State indicator water ornament
  ## Source: template input select 
  switch_water_ornament:
    name: Waterbollen
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"
  ## State indicator sunscreen
  ## Source: template input select 
  blinds_sunscreen:
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"
  ## Reason indicator sunscreen
  ## Source: template input select 
  blinds_sunscreen_reason:
    name: Nieuwe hue scene
    icon: mdi:lightbulb
    options:
      - Regen
      - Bewolkt
      - Stand zon
      - Overbrugt
      - Tijd
      - "-"
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ## State indicator garden lights
  ## Source: template input select 
  light_garden:
    name: Tuin verlichting
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"

sensor:
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Switch garden
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_power
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "W"
    value_template: "{{ value_json.power }}"
    icon: "mdi:flash"
  ## Switch garden
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_energy
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.energy }}"
    icon: "mdi:power-plug"
  ## Switch garden
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_temperature
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"
    device_class: "temperature"
  ## Switch garden
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_voltage
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "V"
    value_template: "{{ value_json.voltage }}"
    icon: "mdi:alpha-v"
  ## Switch garden
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_linkquality
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"
    icon: "mdi:signal"
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## sensor - Test
  ##-----------------------------------------------------------------------------------------------

switch:
  ##-----------------------------------------------------------------------------------------------
  ## switch - Active
  ##-----------------------------------------------------------------------------------------------
  ## Switch garden lights
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_lights
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_l1 }}"
    command_topic: "zigbee2mqtt/aqara_switch_garden/l1/set"
  ## Switch garden spare
  ## Source Xiaomi Aqara LLKZMK11LM
  - platform: "mqtt"
    name: switch_garden_spare
    state_topic: "zigbee2mqtt/aqara_switch_garden"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_l2 }}"
    command_topic: "zigbee2mqtt/aqara_switch_garden/l2/set"
  
  ##-----------------------------------------------------------------------------------------------
  ## switch - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switch - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## switch - Test
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################