## Package file for Home Assistant, used for all alarm sensors and
## associated automations and scripts
## Type: Home Assistant yaml file
## Date added: 2020-02-26
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################

homeassistant:
  customize:
    ## Binary sensors
    binary_sensor.door_refrigerator:
      friendly_name: Koelkast deur
    # binary_sensor.freezer_door:
    #   friendly name: Vriezer deur  
    binary_sensor.motion_office:
      friendly_name: Bewegingssensor kantoor
    ## Link quality sensors
    sensor.door_refrigerator_linkquality:
      friendly_name: Koelkastdeur (link quality)
    sensor.motion_office_linkquality:
      friendly_name: Bewegingssensor kantoor (link quality)

###############################################################################
#  Entities
###############################################################################

input_boolean:
  ## Generic alarm input switch
  alarm_generic_alarm:
    name: Algemeen alarm
  ## Dummy inputs for doors and windows, will be replaced with sensors in the future
  ## Groundfloor
  dummy_groundfloor_front_window:
    name: Voorraam benedenverdieping (dummy)
    icon: mdi:window-closed-variant
  dummy_garden_door:
    name: Tuindeur (dummy)
    icon: mdi:door-closed
  dummy_groundfloor_hallway_door:
    name: Tussendeur woonkamer (dummy)
    icon: mdi:door-closed
  dummy_hallway_storage_door:
    name: Tussendeur berging (dummy)
    icon: mdi:door-closed
  dummy_metering_cabinet_door:
    name: Meterkast deur (dummy)
    icon: mdi:door-closed
  dummy_rest_room_door:
    name: Toiletdeur (dummy)
    icon: mdi:door-closed
  dummy_freezer_door:
    name: Vriezerdeur (dummy)
    icon: mdi:door-closed
  ## First floor
  dummy_bath_room_door:
    name: Badkamer deur (dummy)
    icon: mdi:door-closed
  dummy_bed_room_door:
    name: Slaapkamer deur (dummy)
    icon: mdi:door-closed
  dummy_bed_room_window_left:
    name: Slaapkamer raam links (dummy)
    icon: mdi:window-closed-variant
  dummy_bed_room_window_right:
    name: Slaapkamer raam rechts (dummy)
    icon: mdi:window-closed-variant
  dummy_first_floor_hallway_door:
    name: Tussendeur 1e verdieping (dummy)
    icon: mdi:door-closed
  dummy_office_door:
    name: Kantoor deur (dummy)
    icon: mdi:door-closed
  dummy_office_window:
    name: Kantoor raam (dummy)
    icon: mdi:window-closed-variant
  dummy_side_room_window:
    name: Kastenkamer raam (dummy)
    icon: mdi:window-closed-variant
  ## Second floor
  dummy_heating_room_door:
    name: Ketelkast deur (dummy)
    icon: mdi:door-closed
  dummy_kims_room_door:
    name: Kamer Kim (dummy)
    icon: mdi:door-closed
  dummy_kims_room_window_left:
    name: Kamer Kim raam links (dummy)
    icon: mdi:window-closed-variant
  dummy_kims_room_window_right:
    name: Kamer Kim raam rechts (dummy)
    icon: mdi:window-closed-variant
  ## Special pupose test switches
  dummy_garbage_bin_bio:
    name: GFT bak (dummy)
    icon: mdi:delete-outline
  dummy_garbage_bin_plastic:
    name: PMD bak (dummy)
    icon: mdi:delete-outline

binary_sensor:
  ## Door/window sensors (Xiaomi)
  - platform: mqtt
    name: door_refrigerator
    state_topic: "zigbee2mqtt/aqara_refrigerator_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"

  ## Motion sensors (Xiaomi)
  - platform: mqtt
    name: motion_office
    state_topic: "zigbee2mqtt/mijia_office_motion"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

  ## Binary sensor based on the state of input_boolean.alarm_generic_alarm. Used for lovelace tab Home 
  - platform: template
    sensors:
      alarm_generic_alarm:
        friendly_name: Algemeen alarm
        value_template: >-
          {{ is_state('input_boolean.alarm_generic_alarm', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/alarm48_' ~ states('input_boolean.alarm_generic_alarm') ~ '.png'}}
  ## Door open sensor (only outside doors are monitored)
  - platform: template
    sensors:
      door_all_doors:
        friendly_name: Alle deuren
        value_template: >-
          {{ is_state('binary_sensor.door_front_door', 'on')
            or is_state('binary_sensor.door_storage_door', 'on')
            or is_state('input_boolean.dummy_garden_door', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/door48_' ~ states('binary_sensor.door_all_doors') ~ '.png'}}
  ## Window open sensor
  - platform: template
    sensors:
      door_all_windows:
        friendly_name: Alle ramen
        value_template: >-
          {{ is_state('input_boolean.dummy_groundfloor_front_window', 'on')
            or is_state('input_boolean.dummy_office_window', 'on')
            or is_state('input_boolean.dummy_side_room_window', 'on')
            or is_state('input_boolean.bedroom_window_l', 'on')
            or is_state('input_boolean.bedroom_window_r', 'on') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/window48_' ~ states('binary_sensor.door_all_windows') ~ '.png'}}

sensor:
  ## Refridgerator door link quality status monitoring sensor
  - platform: "mqtt"
    name: door_refrigerator_linkquality
    state_topic: "zigbee2mqtt/aqara_refrigerator_door"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

  ## Motion sensor office link quality status monitoring sensor
  - platform: "mqtt"
    name: motion_office_linkquality
    state_topic: "zigbee2mqtt/mijia_office_motion"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

  ## Sensor alarm status sensor - last update
  - platform: "mqtt"
    name: alert_sensors_update
    state_topic: "home/alert/sensor_update"
    value_template: "{{ value_json.device }}"
    json_attributes_topic: "home/alert/sensor_update"
  ## Sensor alarm status sensor - battery
  - platform: "mqtt"
    name: alert_sensors_battery
    state_topic: "home/alert/sensor_battery"
    value_template: "{{ value_json.device }}"
    json_attributes_topic: "home/alert/sensor_battery"
  ## Sensor alarm status Water meter
  - platform: "mqtt"
    name: alert_water_meter
    state_topic: "home/alert/water_meter_update"
    value_template: "{{ value_json.device }}"
    json_attributes_topic: "home/alert/water_meter_update"

###############################################################################
#  Groups
###############################################################################


###############################################################################
#  Automations
###############################################################################

automation:
  ## Test if refigerator door or freezer door is open for more then xx minutes
  - alias: "Alarm refrigerator door open"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_refrigerator
        to: "on"
        for: "00:10:00"
#      - platform: state
#        entity_id:
#          - binary_sensor.freezer_door
#        to: "on"
#        for: '00:10:00'
    action:
      - service: script.notify_prowl
        data_template:
          value1: "Alarm: "
          value2: "{{ trigger.to_state.attributes.friendly_name }}"
          value3: " meer dan 10 minuten geopend"
          who: "ralph"
          prio: 2
      - service: homeassistant.turn_on
        entity_id: input_boolean.alarm_generic_alarm

  ## Test if alarm is gereset and perform actions
  - alias: "Notification alarm state reset"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.alarm_generic_alarm
        to: "off"
    action:
      - service: script.notify_prowl
        data_template:
          value1: "Alarm op: "
          value2: "{{ now().day }}-{{ now().month }}-{{ now().year }}"
          value3: " om {{ now().hour }}:{{ now().minute }} gereset"
          who: "ralph"
          prio: -2

###############################################################################
#  Templates
###############################################################################


###############################################################################
#  Scripts
###############################################################################
script:
  ## script for checking if alerts were generated during night time or absence of people
  ## resets the mqtt topic to passive after processing
  alert_check_active_alerts:
    alias: check actieve sensor alarmen
    sequence:
      - service: script.notify_prowl
        data_template:
          value1: >-
            {% if (state_attr('sensor.alert_sensors_update','status') == "active") %}
              {{state_attr('sensor.alert_sensors_update','time') }}: Sensor {{ state_attr('sensor.alert_sensors_update','sensor') }} is niet meer geupdate.
            {% else %}
              Er zijn geen actieve sensor update alarmen.
            {% endif %}
          value2: ""
          value3: ""
          who: "ralph"
          prio: -2
      - service: mqtt.publish
        data_template:
          topic: "home/alert/sensor_update"
          retain: true
          payload_template: >-
            {% set timestamp = as_timestamp(now()) | timestamp_custom('%H:%M') %}
            {{ {
              "time": timestamp,
              "sensor": "none",
              "topic": "last update",
              "status" : "passive"
            }|tojson }}
      - delay: 
          milliseconds: 500
      - service: script.notify_prowl
        data_template:
          value1: >-
            {% if (state_attr('sensor.alert_sensors_battery','status') == "active") %}
              {{state_attr('sensor.alert_sensors_battery','time') }}: {{ state_attr('sensor.alert_sensors_battery','sensor') }} niveau is laag.
            {% else %}
              Er zijn geen actieve sensor batterij alarmen.
            {% endif %}
          value2: ""
          value3: ""
          who: "ralph"
          prio: -2
      - service: mqtt.publish
        data_template:
          topic: "home/alert/sensor_battery"
          retain: true
          payload_template: >-
            {% set timestamp = as_timestamp(now()) | timestamp_custom('%H:%M') %}
            {{ {
              "time": timestamp,
              "sensor": "none",
              "topic": "battery",
              "status" : "passive"
            }|tojson }}
      - delay: 
          milliseconds: 500
      - service: script.notify_prowl
        data_template:
          value1: >-
            {% if (state_attr('sensor.alert_water_meter','status') == "active") %}
              {{state_attr('sensor.alert_water_meter','time') }}: Sensor {{ state_attr('sensor.alert_water_meter','sensor') }} is niet meer geupdate.
            {% else %}
              Er zijn geen actieve water meter alarmen.
            {% endif %}
          value2: ""
          value3: ""
          who: "ralph"
          prio: -2
      - service: mqtt.publish
        data_template:
          topic: "home/alert/water_meter_update"
          retain: true
          payload_template: >-
            {% set timestamp = as_timestamp(now()) | timestamp_custom('%H:%M') %}
            {{ {
              "time": timestamp,
              "sensor": "Water meter",
              "topic": "last update",
              "status" : "passive"
            }|tojson }}

###############################################################################
#  Timers
###############################################################################
