## Package file for Home Assistant, used for getting HA-Bridge data via MQTT 
## Type: Home Assistant yaml file
## Date added: 2019-11-11
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ## Media devices from HA Bridge 
    binary_sensor.habridge_television:
      friendly_name: Televisie (via HA Bridge)
    binary_sensor.habridge_smarttv:
      friendly_name: Smart-TV (via HA Bridge)
    binary_sensor.habridge_mediaplayer:
      friendly_name: Mediaplayer (via HA Bridge)
    binary_sensor.habridge_appletv:
      friendly_name: Apple-TV (via HA Bridge)
    binary_sensor.habridge_radio:
      friendly_name: Radio (via HA Bridge)
    binary_sensor.habridge_music:
      friendly_name: Muziek (via HA Bridge)
    binary_sensor.habridge_netflix:
      friendly_name: Netflix (via HA Bridge)
    binary_sensor.habridge_spotify:
      friendly_name: Spotify (via HA Bridge)
    binary_sensor.habridge_program_missed:
      friendly_name: Uitzending gemist (via HA Bridge)  
    binary_sensor.habridge_poweroff:
      friendly_name: Poweroff (via HA-Bridge)
  ##-----------------------------------------------------------------------------------------------
  ## Customizations - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## Customizations - Obsolete
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
binary_sensor:
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Active
  ##-----------------------------------------------------------------------------------------------
  ## Media modes from HA Bridge
  - platform: mqtt
    name: habridge_television
    state_topic: "media_mode/television"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_smarttv
    state_topic: "media_mode/smarttv"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_netflix
    state_topic: "media_mode/netflix"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_spotify
    state_topic: "media_mode/spotify"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_program_missed
    state_topic: "media_mode/program_missed"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_disney
    state_topic: "media_mode/disney"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_amazon
    state_topic: "media_mode/amazon"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_pathe
    state_topic: "media_mode/pathe"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_mediaplayer
    state_topic: "media_mode/mediaplayer"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_appletv
    state_topic: "media_mode/appletv"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_radio
    state_topic: "media_mode/radio"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_music
    state_topic: "media_mode/music"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    name: habridge_poweroff
    state_topic: "media_mode/poweroff"
    off_delay: 2
    payload_on: "on"
    payload_off: "off"
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## binary_sensor - Obsolete
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################