## Package file for Home Assistant, used for presence  
## Type: Home Assistant yaml file
## Date added: 2019-11-17
## Author: R.Bisschops

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  # customize:
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Active
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Check
    ##-----------------------------------------------------------------------------------------------
    ##-----------------------------------------------------------------------------------------------
    ## Customizations - Obsolete
    ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Entities
###############################################################################
input_boolean:
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Active
  ##-----------------------------------------------------------------------------------------------
  ## Button hallway lights
  ## Source: template
  light_hallway_button:
    name: Verlichting halletje
    icon: mdi:lightbulb
  ## Status monitoring hallway lights
  ## Source: template
  light_hallway:
    name: Verlichting halletje
    icon: mdi:lightbulb
  ##-----------------------------------------------------------------------------------------------
  ## input_boolean - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ##input_boolean - Obsolete
  ##-----------------------------------------------------------------------------------------------

input_select:
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Active
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_select - Obsolete
  ##-----------------------------------------------------------------------------------------------
  ## State indicator hallway lights
  ## Source: template 
  light_hallway:
    name: Verlichting halletje
    options:
      - "on"
      - "off"
      - "auto"
      - "hand"

input_number:
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Active
  ##-----------------------------------------------------------------------------------------------
  ## Long timer hallway lights (used in Node_RED)
  ## Source: template
  light_hallway_long_timer:
    name: Halletje timer lang (min)
    initial: 5
    min: 1
    max: 30
    step: 1 
  ## Short timer hallway lights (used in Node_RED) 
  ## Source: template
  light_hallway_short_timer:
    name: Halletje timer kort (min)
    initial: 2
    min: 1
    max: 30
    step: 1
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Check
  ##-----------------------------------------------------------------------------------------------
  ##-----------------------------------------------------------------------------------------------
  ## input_number - Obsolete
  ##-----------------------------------------------------------------------------------------------

###############################################################################
##  Groups
###############################################################################

###############################################################################
##  Automations
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################

###############################################################################
##  Templates
###############################################################################

###############################################################################
##  Scripts
###############################################################################

###############################################################################
##  Timers
###############################################################################